<script lang="ts">
  // Phase 5.0.2 `ptygrid init` — the preview modal (spec-init-5.0.2.md §6).
  //
  // Shows what was detected (found AND not found), where the file would go,
  // the generated YAML (editable), the self-check badge, and — when a config
  // already exists — the sidecar destination plus a line-by-line two-pane diff.
  // Nothing here writes on its own: `init_scan`/`init_preview` never touch the
  // disk and `init_write` re-runs `parse_config` on whatever the textarea holds.
  //
  // `dir` is always passed explicitly by the caller: `init_dir()` deliberately
  // refuses to fall back to the launch cwd (`no_target_dir:`), so an omitted
  // `dir` is a frontend bug, not a user error.
  import { onMount } from "svelte";
  import { msg } from "./i18n.svelte";
  import { invokeCmd, isTauri } from "./tauri";
  import type {
    ConfigOrigin,
    InitPreview,
    InitProbeReport,
    InitTarget,
    InitWriteResult,
    LocalLlmEndpoint,
  } from "./types";

  let {
    dir,
    onclose,
    onwritten,
  }: {
    /** Absolute working folder to scan and write into. Never omitted. */
    dir: string;
    onclose: () => void;
    /** Called after a successful write, before the modal closes. */
    onwritten: (result: InitWriteResult) => void;
  } = $props();

  const SIDECAR_FILE_NAME = "ptygrid.init.yml";
  /** Above this many DP cells the diff falls back to unaligned side-by-side. */
  const DIFF_MAX_CELLS = 4_000_000;
  /** Whole-probe budget on the backend (PROBE_TOTAL_BUDGET), stated in the UI
   * so a press that takes a few seconds does not read as a hang. */
  const PROBE_BUDGET_SECONDS = 3;
  /** u16, so anything above this cannot even reach the command. */
  const MAX_PORT = 65535;

  let m = $derived(msg());

  let target = $state<InitTarget>("project");
  let preview = $state<InitPreview | null>(null);
  /** The text that will actually be written (`init_write` takes it verbatim). */
  let content = $state("");
  /** True once the textarea diverges from what `init_preview` generated. There
   * is no check-only command, so an edited buffer cannot show ✅/❌ until the
   * write re-runs `parse_config` — the badge says so instead of guessing. */
  let edited = $state(false);
  let loading = $state(false);
  let writing = $state(false);
  /** Preview-side failure (scan/generate). Write failures use `writeError`. */
  let loadError = $state<string | null>(null);
  let writeError = $state<string | null>(null);
  /** Backend text of the last refused write (shown verbatim under the reason). */
  let writeErrorDetail = $state<string | null>(null);
  /** Inline confirmation (GitPanel's `operationMessage` pattern). The global
   * toast stack sits below this modal, so the panel reports its own outcome. */
  let statusMessage = $state<string | null>(null);

  // --- local LLM probe (5.0.2 addendum) ---
  /** Last `init_probe_llm` result, or null while the button has never been
   * pressed. Null is what keeps every generated byte identical to 5.0.2: the
   * `llm` argument is then omitted from `init_preview` entirely. */
  let probe = $state<InitProbeReport | null>(null);
  let probing = $state(false);
  let probeError = $state<string | null>(null);
  /** Backend text of a refused probe (same reason + verbatim detail pattern as
   * `writeError` / `writeErrorDetail`). */
  let probeErrorDetail = $state<string | null>(null);
  /** Raw text of the extra-port field. Parsed on press, never stored anywhere:
   * this panel keeps no browser storage. */
  let extraPortsText = $state("");
  /** True when a probe produced a preview that differs from a hand-edited
   * buffer. The generated text is NOT dropped in silently — the user picks
   * (see `applyGenerated` / `keepEdits`). */
  let applyPending = $state(false);
  /** Chosen model per endpoint, keyed by port. `render_config` writes
   * `models[0]` into `--model` and the rest into the `# 他に:` comment, so the
   * choice is expressed by reordering `models` before handing the endpoints to
   * `init_preview` — no extra wire field, no generated text built here.
   * Recomputed from scratch on every probe (`runProbe`). */
  let modelChoice = $state<Record<number, string | undefined>>({});

  let scan = $derived(preview?.scan ?? null);

  let probeEndpoints = $derived<LocalLlmEndpoint[]>(probe?.endpoints ?? []);
  /** The ports actually hit (defaults + accepted extras), as the backend
   * deduplicated and sorted them — not what was typed. */
  let probedPortList = $derived((probe?.probedPorts ?? []).join(" / "));

  // --- default model pick (frontend-only, deliberately) ---
  //
  // `ollama list` order says nothing about what a model is for, so the first
  // entry can be an image model (`x/flux2-klein:latest`) and `models[0]` would
  // land in `--model`. The guess below only moves the *default* selection; the
  // backend keeps its single rule (`models[0]`) and stays unaware of this, so
  // there is no second copy of the heuristic to drift.

  /** Families that are never a chat model, matched anywhere in the name. Each
   * is long and distinctive enough that a substring hit cannot realistically
   * be an ordinary chat model, and one entry covers the whole family:
   * `embed` → `nomic-embed-text` / `text-embedding-3` / `mxbai-embed-large`,
   * `rerank` → `bge-reranker-v2`, `diffusion` → `stable-diffusion-3.5` and
   * `stablediffusion`, `whisper` → `whisper-large-v3`. */
  const NON_CHAT_SUBSTRINGS = ["embed", "rerank", "diffusion", "whisper"];

  /** Families whose names are too short to match as substrings — `clip` sits
   * inside `eclipse`, `sd` inside plenty of ordinary words. These are matched
   * only as a whole token between delimiters (`/`, `-`, `_`, `.`, `:`), with a
   * trailing version number stripped so `flux2` and `sd35` still count. */
  const NON_CHAT_TOKENS = ["sd", "sdxl", "flux", "clip", "tts", "bge"];

  /** True when the name reads as embedding / image / speech / rerank. Used for
   * the default selection only — nothing is ever removed from the list. */
  function looksNonChat(model: string): boolean {
    const name = model.toLowerCase();
    if (NON_CHAT_SUBSTRINGS.some((word) => name.includes(word))) return true;
    for (const token of name.split(/[^a-z0-9]+/)) {
      if (token === "") continue;
      const base = token.replace(/\d+$/, "");
      if (NON_CHAT_TOKENS.includes(token) || NON_CHAT_TOKENS.includes(base)) {
        return true;
      }
    }
    return false;
  }

  /** First name that does not read as a non-chat model, else `models[0]` —
   * a list of nothing but embedding models still gets a usable default. */
  function defaultModel(models: string[]): string | undefined {
    if (models.length === 0) return undefined;
    return models.find((name) => !looksNonChat(name)) ?? models[0];
  }

  /** `chosen` first, everything else in the order the endpoint reported it.
   * Returns the original array when there is nothing to move, so the endpoint
   * object handed to `init_preview` stays identical in that case. */
  function orderedModels(models: string[], chosen: string | undefined): string[] {
    if (chosen === undefined) return models;
    const at = models.indexOf(chosen);
    if (at <= 0) return models;
    return [chosen, ...models.slice(0, at), ...models.slice(at + 1)];
  }

  /** The `llm` argument for `init_preview`: the probed endpoints with each
   * one's `models` rotated so the chosen model is first. Empty (and therefore
   * omitted by the caller) whenever the probe has never run. */
  function llmForPreview(): LocalLlmEndpoint[] {
    return (probe?.endpoints ?? []).map((endpoint) => {
      const models = orderedModels(endpoint.models, modelChoice[endpoint.port]);
      return models === endpoint.models ? endpoint : { ...endpoint, models };
    });
  }

  /** `init_write` refuses when the destination is `<dir>/ptygrid.yml` and a
   * legacy `mterm.yml` is still there. `existing.legacy` can only be true when
   * `<dir>/ptygrid.yml` is absent (search order), so `!sidecar` + target
   * `project` is exactly the refused case — predictable without writing. */
  let legacyBlocks = $derived(
    preview !== null &&
      preview.target === "project" &&
      !preview.sidecar &&
      preview.scan.existing?.legacy === true,
  );

  let canWrite = $derived(
    preview !== null &&
      !writing &&
      !loading &&
      !probing &&
      (edited || preview.valid),
  );

  function originLabel(origin: ConfigOrigin): string {
    switch (origin) {
      case "project":
        return m.originProject;
      case "launch":
        return m.originLaunch;
      case "global":
        return m.originGlobal;
      case "default":
        return m.originDefault;
    }
  }

  /** Map the CONTRACT error prefixes to a human reason; unknown (plain I/O)
   * errors fall through to the raw backend text. */
  function errorReason(raw: string): string | null {
    if (raw.startsWith("legacy_config:")) return m.initErrLegacy;
    if (raw.startsWith("invalid_config:")) return m.initErrInvalid;
    if (raw.startsWith("no_home:")) return m.initErrNoHome;
    if (raw.startsWith("no_target_dir:")) return m.initErrNoTargetDir;
    if (raw.startsWith("bad_port:")) return m.initErrBadPort;
    return null;
  }

  // --- two-pane line diff (spec §3.4: line based, never a structural merge) ---

  type DiffRow = {
    leftNo: number | null;
    left: string | null;
    rightNo: number | null;
    right: string | null;
    kind: "same" | "removed" | "added" | "changed";
  };

  function splitLines(text: string): string[] {
    return text.replace(/\n$/, "").split("\n");
  }

  function lineDiff(left: string[], right: string[]): DiffRow[] {
    const n = left.length;
    const k = right.length;
    const rows: DiffRow[] = [];
    if ((n + 1) * (k + 1) > DIFF_MAX_CELLS) {
      for (let i = 0; i < Math.max(n, k); i += 1) {
        const l = i < n ? left[i] : null;
        const r = i < k ? right[i] : null;
        rows.push({
          leftNo: l === null ? null : i + 1,
          left: l,
          rightNo: r === null ? null : i + 1,
          right: r,
          kind: l !== null && r !== null && l === r ? "same" : "changed",
        });
      }
      return rows;
    }
    // Classic LCS table, walked forward so equal runs stay aligned.
    const width = k + 1;
    const lcs = new Uint32Array((n + 1) * width);
    for (let i = n - 1; i >= 0; i -= 1) {
      for (let j = k - 1; j >= 0; j -= 1) {
        lcs[i * width + j] =
          left[i] === right[j]
            ? lcs[(i + 1) * width + j + 1] + 1
            : Math.max(lcs[(i + 1) * width + j], lcs[i * width + j + 1]);
      }
    }
    let i = 0;
    let j = 0;
    while (i < n && j < k) {
      if (left[i] === right[j]) {
        rows.push({
          leftNo: i + 1,
          left: left[i],
          rightNo: j + 1,
          right: right[j],
          kind: "same",
        });
        i += 1;
        j += 1;
      } else if (lcs[(i + 1) * width + j] >= lcs[i * width + j + 1]) {
        rows.push({
          leftNo: i + 1,
          left: left[i],
          rightNo: null,
          right: null,
          kind: "removed",
        });
        i += 1;
      } else {
        rows.push({
          leftNo: null,
          left: null,
          rightNo: j + 1,
          right: right[j],
          kind: "added",
        });
        j += 1;
      }
    }
    while (i < n) {
      rows.push({
        leftNo: i + 1,
        left: left[i],
        rightNo: null,
        right: null,
        kind: "removed",
      });
      i += 1;
    }
    while (j < k) {
      rows.push({
        leftNo: null,
        left: null,
        rightNo: j + 1,
        right: right[j],
        kind: "added",
      });
      j += 1;
    }
    return rows;
  }

  let diffLines = $derived.by(() => {
    if (!preview?.sidecar || preview.existingContent === undefined) return null;
    return {
      left: splitLines(preview.existingContent),
      right: splitLines(content),
    };
  });

  let diffTooLarge = $derived(
    diffLines !== null &&
      (diffLines.left.length + 1) * (diffLines.right.length + 1) >
        DIFF_MAX_CELLS,
  );

  let diffRows = $derived(
    diffLines === null ? [] : lineDiff(diffLines.left, diffLines.right),
  );

  // --- commands ---

  /** `offerApply` is set only by the probe: it is the one path where the
   * generated body actually changes, so it is also the only one allowed to ask
   * about replacing a hand-edited buffer. */
  async function refreshPreview(
    next: InitTarget,
    offerApply = false,
  ): Promise<void> {
    if (!isTauri()) {
      loadError = m.tauriOnly;
      return;
    }
    loading = true;
    loadError = null;
    writeError = null;
    writeErrorDetail = null;
    statusMessage = null;
    try {
      // `llm` stays out of the call until a probe has actually run. An empty
      // list and "never probed" generate the same bytes by contract, but
      // omitting it keeps the never-pressed path byte-for-byte the old one.
      const llm = llmForPreview();
      const result = await invokeCmd<InitPreview>("init_preview", {
        dir,
        target: next,
        ...(llm.length > 0 ? { llm } : {}),
      });
      preview = result;
      target = result.target;
      // Keep hand edits across a destination switch: the generated body does
      // not depend on `target` (only `path`/`sidecar` do), so discarding the
      // user's text here would lose work for no reason.
      if (!edited) {
        content = result.content;
        applyPending = false;
      } else if (offerApply && content !== result.content) {
        // A probe asks for new text, but the buffer is the user's. Offer the
        // swap instead of performing it (`applyGenerated`).
        applyPending = true;
      }
    } catch (err) {
      // Keep the last good preview (and therefore `target`): a failed switch to
      // Global — `no_home:` — must leave the Project choice reachable.
      const raw = String(err);
      loadError = errorReason(raw) ?? m.initPreviewFailed(raw);
    } finally {
      loading = false;
    }
  }

  function selectTarget(next: InitTarget): void {
    if (next === target || loading || writing) return;
    void refreshPreview(next);
  }

  /** Read the extra-port field. Only what could never be a `u16` is rejected
   * here — `0` and "more than four extras" are the backend's single `bad_port:`
   * rule and are deliberately left to it, so the two never drift apart. */
  function parseExtraPorts(raw: string): { ports: number[] } | { bad: string } {
    const ports: number[] = [];
    for (const token of raw.split(",")) {
      const trimmed = token.trim();
      if (trimmed === "") continue;
      if (!/^\d+$/.test(trimmed) || Number(trimmed) > MAX_PORT) {
        return { bad: trimmed };
      }
      ports.push(Number(trimmed));
    }
    return { ports };
  }

  /** Explicit, user-initiated only: this is real HTTP against loopback and
   * costs up to the whole-probe budget. Nothing here writes to disk. */
  async function runProbe(): Promise<void> {
    if (probing || loading || writing) return;
    if (!isTauri()) {
      probeError = m.tauriOnly;
      probeErrorDetail = null;
      return;
    }
    const parsed = parseExtraPorts(extraPortsText);
    if ("bad" in parsed) {
      probeError = m.initProbeExtraInvalid(parsed.bad);
      probeErrorDetail = null;
      return;
    }
    probing = true;
    probeError = null;
    probeErrorDetail = null;
    statusMessage = null;
    try {
      // `ports` carries the *extras* only, and is omitted when there are none.
      const report = await invokeCmd<InitProbeReport>(
        "init_probe_llm",
        parsed.ports.length > 0 ? { ports: parsed.ports } : {},
      );
      probe = report;
      // A fresh result gets fresh defaults: a port that answered with a
      // different model list must not keep the previous run's selection.
      const picks: Record<number, string | undefined> = {};
      for (const endpoint of report.endpoints) {
        picks[endpoint.port] = defaultModel(endpoint.models);
      }
      modelChoice = picks;
      // The generated text belongs to the backend: ask it again with the
      // result rather than splicing endpoints into the buffer here.
      await refreshPreview(target, true);
    } catch (err) {
      const raw = String(err);
      const reason = errorReason(raw);
      probeError = reason ?? raw;
      probeErrorDetail = reason === null ? null : raw;
    } finally {
      probing = false;
    }
  }

  /** Picking a model only changes which entry of `models` comes first; the
   * text itself is regenerated by `init_preview`, and `offerApply` keeps the
   * hand-edited-buffer rule identical to the probe's own path. */
  function selectModel(port: number, model: string): void {
    if (modelChoice[port] === model || probing || loading || writing) return;
    modelChoice = { ...modelChoice, [port]: model };
    void refreshPreview(target, true);
  }

  /** Take the probe-aware generated text, dropping the hand edits — only ever
   * from the explicit button under `initProbeApplyAsk`. */
  function applyGenerated(): void {
    if (preview === null) return;
    content = preview.content;
    edited = false;
    applyPending = false;
  }

  function keepEdits(): void {
    applyPending = false;
  }

  function probeBadge(endpoint: LocalLlmEndpoint): {
    text: string;
    kind: "ok" | "warn" | "ng";
    note: string;
  } {
    if (endpoint.anthropic === true) {
      return {
        text: m.initProbeConfirmed,
        kind: "ok",
        note: m.initProbeConfirmedNote,
      };
    }
    if (endpoint.anthropic === false) {
      return {
        text: m.initProbeUnsupported,
        kind: "ng",
        note: m.initProbeUnsupportedNote,
      };
    }
    // null: `/v1/models` answered, which proves nothing about `/v1/messages`.
    return {
      text: m.initProbeUnconfirmed,
      kind: "warn",
      note: m.initProbeUnconfirmedNote,
    };
  }

  async function copyContent(): Promise<void> {
    try {
      await navigator.clipboard.writeText(content);
      writeError = null;
      writeErrorDetail = null;
      statusMessage = m.initCopied;
    } catch (err) {
      statusMessage = null;
      writeError = m.clipboardCopyFailed(err);
      writeErrorDetail = null;
    }
  }

  async function write(): Promise<void> {
    if (!canWrite || preview === null) return;
    if (!isTauri()) {
      writeError = m.tauriOnly;
      return;
    }
    writing = true;
    writeError = null;
    writeErrorDetail = null;
    statusMessage = null;
    try {
      const result = await invokeCmd<InitWriteResult>("init_write", {
        dir,
        target,
        content,
      });
      onwritten(result);
      onclose();
    } catch (err) {
      const raw = String(err);
      const reason = errorReason(raw);
      writeError = reason ?? raw;
      writeErrorDetail = reason === null ? null : raw;
    } finally {
      writing = false;
    }
  }

  function onKeydown(event: KeyboardEvent): void {
    if (event.key !== "Escape" || writing) return;
    // Escape inside the editable preview would throw away hand edits; only the
    // explicit Cancel button does that.
    const el = event.target;
    if (el instanceof HTMLElement && el.tagName === "TEXTAREA") return;
    onclose();
  }

  onMount(() => {
    void refreshPreview(target);
  });
</script>

<svelte:window onkeydown={onKeydown} />

<div class="init-overlay">
  <div class="init-modal" role="dialog" aria-modal="true" aria-label={m.initAria}>
    <header class="init-head">
      <span class="init-title">{m.initTitle}</span>
      <span class="init-spacer"></span>
      <button class="btn btn-small" onclick={onclose} title={m.btnClose}>✕</button>
    </header>

    <div class="init-body">
      {#if loadError}
        <div class="init-error" role="alert">{loadError}</div>
      {:else if loading && preview === null}
        <div class="init-muted">{m.initLoading}</div>
      {/if}

      {#if scan}
        <!-- 1. detection: found AND not found, so an absent guidance block
             always has a visible reason (spec §6-1). -->
        <section class="init-section">
          <div class="init-section-title">{m.initScanHead}</div>
          <dl class="init-facts">
            <dt>{m.initScanDir}</dt>
            <dd class="init-path" title={scan.dir}>{scan.dir}</dd>

            <dt>{m.initScanAgents}</dt>
            <dd class:init-absent={scan.agents.length === 0}>
              {scan.agents.length > 0 ? scan.agents.join(" / ") : m.initValueNone}
            </dd>

            <dt>{m.initScanProject}</dt>
            <dd class:init-absent={scan.projectKinds.length === 0}>
              {scan.projectKinds.length > 0
                ? scan.projectKinds.join(" / ")
                : m.initValueNone}
            </dd>

            <dt>{m.initScanGit}</dt>
            <dd class:init-absent={!scan.gitRepo}>
              {scan.gitRepo ? m.initValueYes : m.initValueNo}
            </dd>

            <dt>{m.initScanRouter}</dt>
            <dd>
              <div class:init-absent={scan.routerPort === null}>
                {scan.routerPort === null
                  ? m.initRouterNone
                  : m.initRouterFound(scan.routerPort)}
              </div>
              <!-- 5.0.2 addendum. Deliberately NOT part of `init_scan`: this
                   is seconds of real HTTP, so it stays an explicit press and
                   the scan keeps its non-blocking contract. -->
              <div class="init-row">
                <button
                  class="btn btn-small"
                  onclick={runProbe}
                  disabled={probing || loading || writing}
                  title={m.btnInitProbeTitle}
                >
                  {probing ? m.btnInitProbing : m.btnInitProbe}
                </button>
                <label class="init-port-label">
                  <span>{m.initProbeExtraLabel}</span>
                  <input
                    class="init-port-input"
                    type="text"
                    inputmode="numeric"
                    autocomplete="off"
                    spellcheck="false"
                    placeholder={m.initProbeExtraPlaceholder}
                    bind:value={extraPortsText}
                    disabled={probing}
                  />
                </label>
                <span class="init-muted">{m.initProbeExtraHint}</span>
              </div>
              {#if probing}
                <div class="init-muted" role="status">
                  {m.initProbeRunning(PROBE_BUDGET_SECONDS)}
                </div>
              {/if}
              <div class="init-note">{m.initProbeHint(PROBE_BUDGET_SECONDS)}</div>
              {#if probeError}
                <div class="init-error" role="alert">
                  {probeError}
                  {#if probeErrorDetail}
                    <pre class="init-error-text">{probeErrorDetail}</pre>
                  {/if}
                </div>
              {/if}
            </dd>

            {#if probe}
              <!-- The press always says what came of it, including "nothing
                   answered" — an unchanged panel would read as a dead button. -->
              <dt>{m.initProbeResult}</dt>
              <dd>
                {#if probeEndpoints.length === 0}
                  <div class="init-absent">
                    {m.initProbeNoAnswer(probedPortList)}
                  </div>
                {:else}
                  <div class="init-note">{m.initProbeProbed(probedPortList)}</div>
                {/if}
                {#if probe.timedOut}
                  <div class="init-warn" role="note">
                    {m.initProbeTimedOut(PROBE_BUDGET_SECONDS)}
                  </div>
                {/if}
              </dd>

              {#each probeEndpoints as endpoint (endpoint.port)}
                {@const badge = probeBadge(endpoint)}
                <dt class="init-path">127.0.0.1:{endpoint.port}</dt>
                <dd>
                  <span>{endpoint.label}</span>
                  <span
                    class="init-tag"
                    class:init-tag-ok={badge.kind === "ok"}
                    class:init-tag-warn={badge.kind === "warn"}
                    class:init-tag-ng={badge.kind === "ng"}>{badge.text}</span
                  >
                  {#if endpoint.models.length === 1}
                    <span
                      class="init-path init-models"
                      title={endpoint.models[0]}
                      >{m.initProbeModels(endpoint.models[0], 1)}</span
                    >
                  {/if}
                  {#if endpoint.models.length > 1}
                    <!-- More than one on offer, so the pick is the user's. The
                         summary span is dropped here on purpose: `models[0]`
                         is no longer what gets written once a model has been
                         chosen — the select is. -->
                    <div class="init-row">
                      <label class="init-model-label">
                        <span>{m.initProbeModelLabel}</span>
                        <select
                          class="init-model-select"
                          title={m.initProbeModelTitle}
                          value={modelChoice[endpoint.port] ??
                            endpoint.models[0]}
                          onchange={(e) =>
                            selectModel(endpoint.port, e.currentTarget.value)}
                          disabled={probing || loading || writing}
                        >
                          <!-- Every model the endpoint reported, in its own
                               order. The guess picks a default; it never hides
                               a choice. -->
                          {#each endpoint.models as model, index (index)}
                            <option value={model}>{model}</option>
                          {/each}
                        </select>
                      </label>
                      <span class="init-muted"
                        >{m.initProbeModelCount(endpoint.models.length)}</span
                      >
                    </div>
                    <div class="init-note">{m.initProbeModelNote}</div>
                  {/if}
                  <div class="init-note">{badge.note}</div>
                </dd>
              {/each}
            {/if}

            <dt>{m.initScanExisting}</dt>
            <dd class:init-absent={scan.existing === null}>
              {#if scan.existing}
                <span class="init-path" title={scan.existing.path}
                  >{scan.existing.path}</span
                >
                <span class="init-tag">{originLabel(scan.existing.origin)}</span>
                {#if scan.existing.legacy}
                  <span class="init-tag init-tag-warn">{m.initLegacyTag}</span>
                {/if}
              {:else}
                {m.initValueNo}
              {/if}
            </dd>
          </dl>
          <div class="init-note">{m.initScanNote}</div>
        </section>
      {/if}

      {#if preview}
        <!-- 2. destination + Project/Global choice. The Global note states the
             consequence (trust-free autostart) without recommending it. -->
        <section class="init-section">
          <div class="init-section-title">{m.initTargetHead}</div>
          <div class="init-row">
            <span
              class="init-seg"
              role="group"
              aria-label={m.initTargetAria}
            >
              <button
                class="seg-btn"
                class:seg-active={target === "project"}
                onclick={() => selectTarget("project")}
                disabled={loading || writing}
              >
                {m.initTargetProject}
              </button>
              <button
                class="seg-btn"
                class:seg-active={target === "global"}
                onclick={() => selectTarget("global")}
                disabled={loading || writing}
              >
                {m.initTargetGlobal}
              </button>
            </span>
            <span class="init-muted">{m.initDestLabel}</span>
            <span class="init-path init-dest" title={preview.path}
              >{preview.path}</span
            >
          </div>
          {#if target === "global"}
            <div class="init-warn" role="note">{m.initGlobalWarn}</div>
          {:else}
            <div class="init-note">{m.initTargetProjectNote}</div>
          {/if}
        </section>

        {#if legacyBlocks && scan?.existing}
          <div class="init-warn" role="alert">
            {m.initLegacyWarn(scan.existing.path)}
          </div>
        {/if}

        {#if preview.sidecar}
          <!-- 4. sidecar: name of the destination, the untouched existing file,
               and the line-by-line two-pane diff. -->
          <section class="init-section">
            <div class="init-section-title">{m.initSidecarHead}</div>
            <div class="init-note">{m.initSidecarNote(SIDECAR_FILE_NAME)}</div>
          </section>
        {/if}

        <!-- 3. editable preview + self-check badge + the autostart statement. -->
        <section class="init-section">
          <div class="init-section-title">{m.initPreviewHead}</div>
          {#if applyPending && edited}
            <!-- The probe regenerated the file, but this buffer is the user's:
                 the swap is offered, never done behind their back. -->
            <div class="init-warn" role="note">
              {m.initProbeApplyAsk}
              <div class="init-row">
                <button class="btn btn-small" onclick={applyGenerated}>
                  {m.btnInitProbeApply}
                </button>
                <button class="btn btn-small" onclick={keepEdits}>
                  {m.btnInitProbeKeep}
                </button>
              </div>
            </div>
          {/if}
          <textarea
            class="init-preview"
            aria-label={m.initPreviewAria}
            spellcheck="false"
            value={content}
            oninput={(e) => {
              content = e.currentTarget.value;
              edited = content !== preview?.content;
            }}
            disabled={writing}
          ></textarea>
          <div class="init-row">
            {#if edited}
              <span class="init-badge init-badge-edited">{m.initCheckEdited}</span>
            {:else if preview.valid}
              <span class="init-badge init-badge-ok">{m.initCheckOk}</span>
            {:else}
              <span class="init-badge init-badge-ng">{m.initCheckNg}</span>
            {/if}
          </div>
          {#if !edited && !preview.valid && preview.error}
            <pre class="init-error-text">{preview.error}</pre>
          {/if}
          <div class="init-note">{m.initAutostartNote}</div>
        </section>

        {#if diffLines}
          <section class="init-section">
            <div class="init-section-title">{m.initDiffHead}</div>
            {#if diffTooLarge}
              <div class="init-note">{m.initDiffTooLarge}</div>
            {/if}
            <div class="init-diff-head">
              <span>{m.initDiffLeft}</span>
              <span>{m.initDiffRight}</span>
            </div>
            <div class="init-diff">
              {#each diffRows as row, index (index)}
                <div class="init-diff-row init-diff-{row.kind}">
                  <span class="init-diff-no">{row.leftNo ?? ""}</span>
                  <span class="init-diff-cell">{row.left ?? ""}</span>
                  <span class="init-diff-no">{row.rightNo ?? ""}</span>
                  <span class="init-diff-cell">{row.right ?? ""}</span>
                </div>
              {/each}
            </div>
          </section>
        {/if}

        {#if statusMessage}
          <div class="init-status" role="status">{statusMessage}</div>
        {/if}

        {#if writeError}
          <div class="init-error" role="alert">
            {writeError}
            {#if writeErrorDetail}
              <pre class="init-error-text">{writeErrorDetail}</pre>
            {/if}
          </div>
        {/if}
      {/if}
    </div>

    <footer class="init-foot">
      <button
        class="btn"
        onclick={write}
        disabled={!canWrite}
        title={m.btnInitWrite}
      >
        {writing ? m.btnInitWriting : m.btnInitWrite}
      </button>
      <!-- The escape hatch: always available, even when the self-check fails. -->
      <button
        class="btn"
        onclick={copyContent}
        disabled={content === ""}
        title={m.btnInitCopyTitle}
      >
        {m.btnInitCopy}
      </button>
      <span class="init-spacer"></span>
      <button class="btn" onclick={onclose} disabled={writing}>
        {m.btnCancel}
      </button>
    </footer>
  </div>
</div>

<style>
  .init-overlay {
    position: fixed;
    inset: 0;
    z-index: 200;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #000000aa;
  }

  .init-modal {
    display: flex;
    flex-direction: column;
    width: min(920px, 92vw);
    max-height: 88vh;
    background: #1e1e1e;
    border: 1px solid #444;
    border-radius: 6px;
    box-shadow: 0 8px 24px #0008;
    color: #ccc;
    font-size: 12px;
  }

  .init-head,
  .init-foot {
    flex: 0 0 auto;
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 10px;
  }

  .init-head {
    background: #252526;
    border-bottom: 1px solid #3a3a3a;
    border-radius: 6px 6px 0 0;
  }

  .init-foot {
    background: #252526;
    border-top: 1px solid #3a3a3a;
    border-radius: 0 0 6px 6px;
  }

  .init-title {
    color: #fff;
    font-weight: 600;
  }

  .init-spacer {
    flex: 1 1 auto;
  }

  .init-body {
    flex: 1 1 auto;
    min-height: 0;
    overflow-y: auto;
    padding: 4px 10px 10px;
  }

  .init-section {
    padding: 8px 0;
    border-bottom: 1px solid #333;
  }

  .init-section-title {
    color: #999;
    font-weight: 600;
    text-transform: uppercase;
    font-size: 10px;
    letter-spacing: 0.03em;
    padding-bottom: 4px;
  }

  .init-row {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    padding: 4px 0;
  }

  .init-facts {
    display: grid;
    grid-template-columns: max-content 1fr;
    gap: 2px 10px;
    margin: 0;
  }

  .init-facts dt {
    color: #888;
  }

  .init-facts dd {
    margin: 0;
    color: #ddd;
    overflow-wrap: anywhere;
  }

  .init-absent {
    color: #888;
  }

  .init-path {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    overflow-wrap: anywhere;
  }

  .init-dest {
    color: #ddd;
  }

  .init-tag {
    display: inline-block;
    margin-left: 6px;
    padding: 0 5px;
    border-radius: 8px;
    background: #333;
    color: #bbb;
    font-size: 10px;
  }

  .init-tag-warn {
    background: #4b3a1e;
    color: #d7ba7d;
  }

  .init-tag-ok {
    background: #23361f;
    color: #4caf50;
  }

  .init-tag-ng {
    background: #4b1e1e;
    color: #f1b0b0;
  }

  .init-models {
    margin-left: 6px;
    color: #bbb;
  }

  .init-model-label {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    color: #888;
    min-width: 0;
  }

  .init-model-select {
    max-width: 28em;
    background: #1b1b1b;
    color: #ddd;
    border: 1px solid #444;
    border-radius: 4px;
    padding: 2px 6px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
  }

  .init-model-select:disabled {
    opacity: 0.45;
  }

  .init-port-label {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    color: #888;
  }

  .init-port-input {
    width: 12em;
    background: #1b1b1b;
    color: #ddd;
    border: 1px solid #444;
    border-radius: 4px;
    padding: 2px 6px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
  }

  .init-port-input:disabled {
    opacity: 0.45;
  }

  .init-note {
    color: #888;
    padding: 4px 0 0;
  }

  .init-muted {
    color: #888;
  }

  .init-warn {
    color: #d7ba7d;
    background: #3a301e;
    border: 1px solid #5a4a2a;
    border-radius: 4px;
    padding: 5px 8px;
    margin: 6px 0;
  }

  .init-status {
    color: #9cc4e4;
    background: #23303a;
    border: 1px solid #35506b;
    border-radius: 4px;
    padding: 5px 8px;
    margin: 6px 0;
  }

  .init-error {
    color: #f1b0b0;
    background: #4b1e1e;
    border: 1px solid #6b2b2b;
    border-radius: 4px;
    padding: 5px 8px;
    margin: 6px 0;
  }

  .init-error-text {
    margin: 4px 0 0;
    white-space: pre-wrap;
    overflow-wrap: anywhere;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
    color: #f1b0b0;
  }

  .init-seg {
    display: inline-flex;
    align-items: center;
    border: 1px solid #444;
    border-radius: 4px;
    overflow: hidden;
  }

  .seg-btn {
    background: #2a2a2a;
    color: #aaa;
    border: none;
    border-right: 1px solid #444;
    padding: 3px 8px;
    font-size: 11px;
    cursor: pointer;
  }

  .seg-btn:last-child {
    border-right: none;
  }

  .seg-btn:hover:not(.seg-active):not(:disabled) {
    background: #353535;
    color: #ddd;
  }

  .seg-btn:disabled {
    opacity: 0.45;
    cursor: default;
  }

  .seg-active {
    background: #3b5b7a;
    color: #fff;
  }

  .init-preview {
    width: 100%;
    min-height: 240px;
    resize: vertical;
    background: #1b1b1b;
    color: #ddd;
    border: 1px solid #444;
    border-radius: 4px;
    padding: 6px 8px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
    line-height: 1.5;
    white-space: pre;
  }

  .init-preview:disabled {
    opacity: 0.6;
  }

  .init-badge {
    display: inline-block;
    padding: 1px 8px;
    border-radius: 8px;
    font-size: 11px;
  }

  .init-badge-ok {
    background: #23361f;
    color: #4caf50;
  }

  .init-badge-ng {
    background: #4b1e1e;
    color: #f1b0b0;
  }

  .init-badge-edited {
    background: #3a301e;
    color: #d7ba7d;
  }

  .init-diff-head {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    color: #888;
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    padding-bottom: 2px;
  }

  .init-diff {
    max-height: 260px;
    overflow: auto;
    border: 1px solid #333;
    border-radius: 4px;
    background: #1b1b1b;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 11px;
    line-height: 1.45;
  }

  .init-diff-row {
    display: grid;
    grid-template-columns: 3.5em 1fr 3.5em 1fr;
    gap: 0 6px;
  }

  .init-diff-no {
    color: #666;
    text-align: right;
    -webkit-user-select: none;
    user-select: none;
  }

  .init-diff-cell {
    white-space: pre-wrap;
    overflow-wrap: anywhere;
    color: #ccc;
  }

  .init-diff-same .init-diff-cell {
    color: #999;
  }

  .init-diff-removed {
    background: #3a2323;
  }

  .init-diff-added {
    background: #23361f;
  }

  .init-diff-changed {
    background: #2f2a1e;
  }

  .btn {
    background: #333;
    color: #ddd;
    border: 1px solid #444;
    border-radius: 4px;
    padding: 3px 8px;
    font-size: 12px;
    cursor: pointer;
  }

  .btn:hover:not(:disabled) {
    background: #3d3d3d;
  }

  .btn:disabled {
    opacity: 0.45;
    cursor: default;
  }

  .btn-small {
    padding: 1px 6px;
    font-size: 11px;
  }
</style>
