// Phase 5.0: declarative DAG orchestration ("Minimum Viable Orchestrator").
//
// Like team_presets.rs, this module is a THIN wrapper over the existing
// allowlist spawn path (`ConfigManager::resolve_def` + `PtyManager::spawn_agent`,
// i.e. exactly what `spawn_agent` uses). Workflows introduce no new spawn
// path and no new trust boundary — anything a workflow can launch, a manual
// `spawn_agent` could too.
//
// Wire contract: CONTRACT.md "Phase 5.0 追加契約". Design: docs/spec-phase5-0.md
// (§2.1 "Workflow モデル", §3.1 "M3 Orchestrator 状態機械"). MVO scope:
// pipeline + fan-out, `join_on: all|any`, completion via AgentStatus == done or
// PTY exit(0). Deferred to 5.0.4: supervisor, handoff, retry, timeout,
// join_on: reply/N, `condition:` predicates.
//
// This module is kept OUTSIDE `lib.rs` and outside the session hot path per
// release discipline (phase3.md).

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use tauri::{AppHandle, Emitter, Listener, Manager, Runtime};

use crate::agent_status::AgentStatus;
use crate::config::{
    ConfigManager, JoinOn, JoinOnName, WorkflowDef, WorkflowPattern, WorkflowStep,
};
use crate::queen_store::QueenStore;
use crate::session::{PtyManager, SessionState};

/// Grid-occupancy cap for partial launch, mirrors `TEAM_SESSION_CAP` /
/// frontend `MAX_PANES`. A workflow step that would exceed this is FAILED
/// with "pane limit" rather than spawning a paneless session.
pub const WORKFLOW_SESSION_CAP: usize = 9;

/// ULID-shaped opaque run identifier. Generated by `spawn_workflow` and
/// returned to the caller (frontend / MCP client) for follow-up `join` and
/// `cancel_workflow`. Wire type is a plain string; the concrete format is not
/// part of the contract, only its opacity.
pub type WorkflowRunId = String;

/// Overall workflow lifecycle. Wire values are lowercase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum WorkflowState {
    /// Reserved: a run is registered before its roots spawn. The MVO
    /// constructs runs directly in `Running` (roots spawn synchronously in
    /// `spawn_workflow`), so nothing produces `Pending` yet; the 5.0.4
    /// scheduler (deferred starts, retry backoff) will. Kept for wire-shape
    /// stability — the frontend already handles the value.
    #[allow(dead_code)]
    Pending,
    Running,
    Succeeded,
    Failed,
    Cancelled,
}

/// One step's lifecycle within a run. `Skipped` is used when a step's
/// predecessor failed and the workflow policy is `fail-fast`; the pane is
/// never spawned.
///
/// Phase 5.0.1: `Deserialize` is derived (in addition to `Serialize`) so a
/// persisted run's `steps_json` can be decoded back into `Vec<StepOutcome>`
/// by `resume_workflow`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum StepState {
    Pending,
    Running,
    Succeeded,
    Failed,
    Skipped,
    Cancelled,
}

/// Per-step outcome inside a `WorkflowRun`.
///
/// Phase 5.0.1: `Deserialize` is derived so `resume_workflow` can decode a
/// persisted run's `steps_json` (see `queen_store::WorkflowRunRow`) back
/// into `Vec<StepOutcome>`; this struct was `Serialize`-only until now.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StepOutcome {
    pub step_id: String,
    pub agent: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<u32>,
    pub state: StepState,
    /// Number of times spawn was attempted (increments on retry; MVO always
    /// leaves this at 1 since retry lands in 5.0.4).
    pub attempts: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Public view of a workflow run, emitted verbatim on the `workflow-state`
/// Tauri event whenever any field changes.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkflowRun {
    pub run_id: WorkflowRunId,
    pub name: String,
    pub state: WorkflowState,
    pub started_at_ms: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ended_at_ms: Option<u64>,
    pub steps: Vec<StepOutcome>,
    /// Pane geometry from the `spawn_workflow` call that created this run.
    /// Not part of the wire contract (no consumer needs it — panes are
    /// already sized by the time the frontend observes them); retained
    /// purely so the 5.0.0.c driver can size any DOWNSTREAM step it spawns
    /// later identically, without threading cols/rows through every
    /// driver-tick caller (`driver_loop` only has the `AppHandle` + the
    /// registry to work from, not the original `spawn_workflow` call site).
    #[serde(skip)]
    cols: u16,
    #[serde(skip)]
    rows: u16,
}

/// One row of `load_config`'s resume-detection query (Phase 5.0.1), shaped
/// for the `workflow-resume-pending` event. A thin projection of
/// `queen_store::WorkflowRunRow` — the frontend only needs enough to render
/// "run '<name>' is still interrupted, resume?" and to name the run in the
/// follow-up `resume_workflow` / `abandon_workflow` call.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkflowResumeCandidate {
    pub run_id: WorkflowRunId,
    pub name: String,
    pub started_at_ms: u64,
}

/// In-memory registry of live and recently-terminated workflow runs. Held as
/// `AppHandle::manage`d state (lib.rs), same pattern as `PtyManager`. MVO
/// keeps the last 100 runs in memory; Phase 5.0.1 adds write-through
/// persistence to the `workflow_runs` SQLite table via `persist_run`, called
/// by every caller of `put` in this module rather than by `put` itself —
/// every call site already holds the `QueenStore` + project dir it needs.
#[derive(Default)]
pub struct WorkflowRegistry {
    inner: Arc<Mutex<HashMap<WorkflowRunId, WorkflowRun>>>,
}

impl WorkflowRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Snapshot a run by id. `None` if the run has been evicted or never
    /// existed. Callers get a clone — the registry lock is never held across
    /// an `AppHandle::emit`.
    pub fn get(&self, run_id: &str) -> Option<WorkflowRun> {
        self.inner.lock().ok().and_then(|g| g.get(run_id).cloned())
    }

    /// Snapshot every run currently held. Used by `list_workflow_runs`.
    pub fn list(&self) -> Vec<WorkflowRun> {
        self.inner
            .lock()
            .map(|g| g.values().cloned().collect())
            .unwrap_or_default()
    }

    /// Replace or insert a run. Callers must have prepared the full snapshot
    /// they want to publish; the registry does not merge fields.
    pub fn put(&self, run: WorkflowRun) {
        if let Ok(mut g) = self.inner.lock() {
            g.insert(run.run_id.clone(), run);
        }
    }
}

/// Wall-clock milliseconds since UNIX_EPOCH; monotonic-enough for run
/// bookkeeping, not for scheduling. Panics on system-time regression only
/// (SystemTime::duration_since panics on error, we swallow it to 0 instead).
fn now_ms() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Random 24-char ULID-ish id. MVO uses a lightweight scheme (no external
/// `ulid` crate dependency yet) — collision probability is negligible for
/// the 100-run in-memory window. Persistence in 5.0.0.c will switch to real
/// ULIDs if the DB layer prefers them.
fn new_run_id() -> WorkflowRunId {
    use std::time::{SystemTime, UNIX_EPOCH};
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    // 16-hex nanos + 8-hex process-local counter = 24 chars.
    use std::sync::atomic::{AtomicU32, Ordering};
    static COUNTER: AtomicU32 = AtomicU32::new(0);
    let ctr = COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("wfr_{:016x}{:08x}", ts, ctr)
}

/// The live session id for a definition name, if one exists (any state
/// except Exited). Same helper as `team_presets::live_session_id`; kept
/// duplicated to avoid a fragile cross-module coupling at MVO scope.
fn live_session_id(manager: &PtyManager, name: &str) -> Option<u32> {
    manager
        .list_sessions()
        .into_iter()
        .find(|s| s.state != SessionState::Exited && s.name.as_deref() == Some(name))
        .map(|s| s.id)
}

/// Steps whose `dependsOn` list is empty — the DAG's roots. These are the
/// steps a fresh run may launch first.
fn root_steps(wf: &WorkflowDef) -> Vec<&WorkflowStep> {
    wf.steps
        .iter()
        .filter(|s| s.depends_on.as_deref().unwrap_or(&[]).is_empty())
        .collect()
}

/// Spawn one step through the existing allowlist path, matching the
/// `team_presets::start_team` idempotency + pane-cap semantics.
fn spawn_step<R: Runtime>(
    app: &AppHandle<R>,
    manager: &PtyManager,
    config: &ConfigManager,
    step: &WorkflowStep,
    reuse_existing: bool,
    cols: u16,
    rows: u16,
) -> StepOutcome {
    let agent = step.agent.clone();
    // Idempotent reuse is only valid for singular steps (pipeline). A fan-out
    // copy must ALWAYS get a fresh pane — the whole point of `fanOut: 3` is 3
    // parallel sessions of the same definition, so the team_presets-style
    // "live same-name session -> skip" rule would collapse the fan to 1.
    let reusable = if reuse_existing {
        live_session_id(manager, &agent)
    } else {
        None
    };
    if let Some(existing) = reusable {
        // Same idempotent skip as team_presets — a workflow re-launching a
        // step whose session already exists reuses the existing pane rather
        // than duplicating it.
        return StepOutcome {
            step_id: step.id.clone(),
            agent,
            session_id: Some(existing),
            state: StepState::Running, // caller will observe completion via AgentStatus/exit
            attempts: 1,
            error: None,
        };
    }
    if manager.list_sessions().len() >= WORKFLOW_SESSION_CAP {
        return StepOutcome {
            step_id: step.id.clone(),
            agent,
            session_id: None,
            state: StepState::Failed,
            attempts: 1,
            error: Some(format!("pane limit ({WORKFLOW_SESSION_CAP}) reached")),
        };
    }
    let spawn = config
        .resolve_def(&agent)
        .and_then(|(def, dir)| manager.spawn_agent(app.clone(), &def, &dir, cols, rows));
    match spawn {
        Ok(id) => StepOutcome {
            step_id: step.id.clone(),
            agent,
            session_id: Some(id),
            state: StepState::Running,
            attempts: 1,
            error: None,
        },
        Err(error) => StepOutcome {
            step_id: step.id.clone(),
            agent,
            session_id: None,
            state: StepState::Failed,
            attempts: 1,
            error: Some(error),
        },
    }
}

/// Deliver a step's `kickoff` message to its inbox mailbox (= definition
/// name) via the durable Queen store, same path team_presets uses.
fn deliver_kickoff(
    store: &QueenStore,
    project_dir: &std::path::Path,
    workflow_name: &str,
    step: &WorkflowStep,
) -> Result<(), String> {
    let Some(kickoff) = step.kickoff.as_ref() else {
        return Ok(());
    };
    store
        .send_inbox(
            project_dir,
            format!("queen:workflow/{workflow_name}"),
            step.agent.clone(),
            format!("workflow:{workflow_name} step:{} kickoff", step.id),
            kickoff.clone(),
        )
        .map(|_| ())
}

/// Launch a named workflow. See CONTRACT.md Phase 5.0 §5.0.3 for the exact
/// wire semantics. MVO scope (5.0.0):
///
/// 1. Validate the workflow exists in the loaded config;
/// 2. For `pipeline`: spawn the single root step and deliver its kickoff;
/// 3. For `fan-out`: spawn N parallel copies of each fanOut-marked root step
///    and deliver each one's kickoff;
/// 4. For `supervisor` / `handoff`: return `Err("pattern not implemented in MVO")`
///    (5.0.4 will land these);
/// 5. Return an initial `WorkflowRun` snapshot with state=Running and each
///    launched step in state=Running.
///
/// Downstream DAG progression (watching for step completion and launching
/// dependent steps) is the 5.0.0.c driver's job — see `start_driver` /
/// `advance_run` below. This function only performs the initial root spawn;
/// everything past that is picked up on the next driver tick.
#[allow(clippy::too_many_arguments)]
pub fn spawn_workflow<R: Runtime>(
    app: &AppHandle<R>,
    manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    registry: &WorkflowRegistry,
    workflow_name: &str,
    cols: u16,
    rows: u16,
) -> Result<WorkflowRun, String> {
    let (cfg, project_dir) = config
        .current()
        .ok_or_else(|| "no config loaded (call load_config first)".to_string())?;
    let wf = cfg
        .workflows
        .as_ref()
        .and_then(|m| m.get(workflow_name))
        .ok_or_else(|| format!("workflow '{workflow_name}' not found in config"))?
        .clone();

    // MVO gates: reject patterns whose runtime driver is not yet implemented.
    match wf.pattern {
        WorkflowPattern::Pipeline | WorkflowPattern::FanOut => {}
        WorkflowPattern::Supervisor | WorkflowPattern::Handoff => {
            return Err(format!(
                "workflow '{workflow_name}': pattern {:?} not implemented in MVO \
                 (lands in Phase 5.0.4)",
                wf.pattern
            ));
        }
    }

    let run_id = new_run_id();
    let started_at_ms = now_ms();
    let mut outcomes: Vec<StepOutcome> = Vec::with_capacity(wf.steps.len());

    // Every non-root step starts Pending.
    for step in &wf.steps {
        let is_root = step.depends_on.as_deref().unwrap_or(&[]).is_empty();
        if !is_root {
            outcomes.push(StepOutcome {
                step_id: step.id.clone(),
                agent: step.agent.clone(),
                session_id: None,
                state: StepState::Pending,
                attempts: 0,
                error: None,
            });
        }
    }

    // Roots launch immediately. fan-out expands roots per fanOut count.
    for step in root_steps(&wf) {
        let copies = match (wf.pattern, step.fan_out) {
            (WorkflowPattern::FanOut, Some(n)) if n >= 2 => n as usize,
            _ => 1,
        };
        // copies == 1 -> singular step (pipeline or un-fanned root): keep the
        // idempotent reuse. copies >= 2 -> fan-out expansion: every copy must
        // spawn fresh.
        let reuse_existing = copies == 1;
        for _ in 0..copies {
            let outcome = spawn_step(app, manager, config, step, reuse_existing, cols, rows);
            // Best-effort kickoff delivery — a failed delivery does NOT flip
            // the step to Failed (the pane is already alive; the agent can
            // still work via manual instruction). The failure is surfaced on
            // the outcome.error field. Same posture team_presets uses.
            if outcome.state == StepState::Running {
                if let Err(err) = deliver_kickoff(store, &project_dir, workflow_name, step) {
                    // Attach as suffix, keeping any earlier error text.
                    let base = outcome.error.clone().unwrap_or_default();
                    let joined = if base.is_empty() {
                        format!("kickoff delivery failed: {err}")
                    } else {
                        format!("{base}; kickoff delivery failed: {err}")
                    };
                    outcomes.push(StepOutcome {
                        error: Some(joined),
                        ..outcome
                    });
                    continue;
                }
            }
            outcomes.push(outcome);
        }
    }

    // Preserve declaration order so callers can render the DAG top-down.
    outcomes.sort_by_key(|o| {
        wf.steps
            .iter()
            .position(|s| s.id == o.step_id)
            .unwrap_or(usize::MAX)
    });

    let state = if outcomes
        .iter()
        .any(|o| o.state == StepState::Running || o.state == StepState::Pending)
    {
        WorkflowState::Running
    } else if outcomes.iter().all(|o| o.state == StepState::Succeeded) {
        WorkflowState::Succeeded
    } else {
        WorkflowState::Failed
    };

    let run = WorkflowRun {
        run_id: run_id.clone(),
        name: workflow_name.to_string(),
        state,
        started_at_ms,
        ended_at_ms: None,
        steps: outcomes,
        cols,
        rows,
    };
    registry.put(run.clone());
    persist_run(store, &project_dir, &run);
    emit_workflow_state(app, &run);
    Ok(run)
}

/// Cancel a running workflow: kill every step's live PTY, mark remaining
/// pending steps CANCELLED, and set the run to `Cancelled`. Idempotent —
/// a terminal (Succeeded/Failed/Cancelled) run is a no-op that returns
/// the current snapshot.
pub fn cancel_workflow(
    manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    registry: &WorkflowRegistry,
    run_id: &str,
) -> Result<WorkflowRun, String> {
    let mut run = registry
        .get(run_id)
        .ok_or_else(|| format!("workflow run '{run_id}' not found"))?;
    if matches!(
        run.state,
        WorkflowState::Succeeded | WorkflowState::Failed | WorkflowState::Cancelled
    ) {
        return Ok(run);
    }
    for outcome in &mut run.steps {
        match outcome.state {
            StepState::Running => {
                if let Some(id) = outcome.session_id {
                    let _ = manager.kill_pty(id);
                }
                outcome.state = StepState::Cancelled;
            }
            StepState::Pending => outcome.state = StepState::Cancelled,
            _ => {}
        }
    }
    run.state = WorkflowState::Cancelled;
    run.ended_at_ms = Some(now_ms());
    registry.put(run.clone());
    // Phase 5.0.1: write-through so a manual cancel is never mistaken for a
    // crash-interrupted run and re-offered as "resume?" after a restart.
    if let Ok(project_dir) = resolve_project_dir(config) {
        persist_run(store, &project_dir, &run);
    }
    Ok(run)
}

/// Every run this project left `state = 'running'` in the Queen DB — a
/// restart loses the in-memory `WorkflowRegistry`, so this is how
/// `load_config` (commands.rs) finds runs to offer resuming (Phase 5.0.1).
/// Read-only; does not touch the registry or spawn anything.
pub fn list_resumable_workflow_runs(
    store: &QueenStore,
    project_dir: &std::path::Path,
) -> Result<Vec<WorkflowResumeCandidate>, String> {
    let rows = store.list_running_workflow_runs(project_dir)?;
    Ok(rows
        .into_iter()
        .map(|row| WorkflowResumeCandidate {
            run_id: row.run_id,
            name: row.name,
            started_at_ms: row.started_at_ms as u64,
        })
        .collect())
}

/// Resume a run left `running` in the Queen DB from before a crash/restart
/// (Phase 5.0.1 "再開"). Succeeded/failed/skipped/cancelled steps are kept
/// exactly as persisted. Any step with a still-`Running` copy lost its PTY
/// when the app died, so every copy of THAT step (terminal or not) is
/// collapsed back to a single fresh `Pending` placeholder — precisely the
/// shape `spawn_workflow` gives a step that has never been spawned. That
/// lets the already-running 5.0.0.c driver (`ready_steps` / `spawn_ready`)
/// pick the run back up on its very next tick with NO changes to that
/// machinery: `spawn_ready`'s retain-then-replace step only recognizes a
/// step as "not yet spawned" via its bare (unsuffixed) id, so leaving a
/// fan-out step's individual suffixed copies (`"<id>#<k>"`) merely flipped
/// in place would never be removed, and the next tick would push a second,
/// colliding set of copies under the same ids. The trade-off: a fan-out step
/// that had already partially joined (e.g. `joinOn: any` with one sibling
/// succeeded and others still running at crash time) re-runs ALL of its
/// copies rather than only the interrupted ones — an accepted narrow edge
/// given the driver does not yet cooperatively cancel in-flight siblings
/// either (5.0.4).
#[allow(clippy::too_many_arguments)]
pub fn resume_workflow<R: Runtime>(
    app: &AppHandle<R>,
    _manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    registry: &WorkflowRegistry,
    run_id: &str,
    cols: u16,
    rows: u16,
) -> Result<WorkflowRun, String> {
    // Idempotent against a repeat call for a run already resumed this
    // session: re-deriving from the (by-now-stale) persisted snapshot would
    // otherwise clobber whatever progress the driver has since made.
    if let Some(existing) = registry.get(run_id) {
        return Ok(existing);
    }
    let (cfg, project_dir) = config
        .current()
        .ok_or_else(|| "no config loaded (call load_config first)".to_string())?;
    let row = store
        .list_running_workflow_runs(&project_dir)?
        .into_iter()
        .find(|r| r.run_id == run_id)
        .ok_or_else(|| format!("workflow run '{run_id}' not found or not resumable"))?;
    let wf = cfg
        .workflows
        .as_ref()
        .and_then(|m| m.get(&row.name))
        .cloned()
        .ok_or_else(|| {
            format!(
                "workflow '{}' is no longer defined in the loaded config",
                row.name
            )
        })?;

    let mut steps: Vec<StepOutcome> = serde_json::from_str(&row.steps_json)
        .map_err(|e| format!("cannot decode persisted workflow steps for '{run_id}': {e}"))?;

    let mut needs_restart: Vec<String> = Vec::new();
    for outcome in &steps {
        if outcome.state == StepState::Running {
            let base = base_id(&outcome.step_id).to_string();
            if !needs_restart.contains(&base) {
                needs_restart.push(base);
            }
        }
    }
    for base in &needs_restart {
        steps.retain(|o| base_id(&o.step_id) != base.as_str());
        let agent = wf
            .steps
            .iter()
            .find(|s| s.id.as_str() == base.as_str())
            .map(|s| s.agent.clone())
            .unwrap_or_default();
        steps.push(StepOutcome {
            step_id: base.clone(),
            agent,
            session_id: None,
            state: StepState::Pending,
            attempts: 0,
            error: None,
        });
    }
    steps.sort_by_key(|o| {
        wf.steps
            .iter()
            .position(|s| s.id == base_id(&o.step_id))
            .unwrap_or(usize::MAX)
    });

    let run = WorkflowRun {
        run_id: row.run_id.clone(),
        name: row.name.clone(),
        state: WorkflowState::Running,
        started_at_ms: row.started_at_ms as u64,
        ended_at_ms: None,
        steps,
        cols,
        rows,
    };
    registry.put(run.clone());
    persist_run(store, &project_dir, &run);
    emit_workflow_state(app, &run);
    Ok(run)
}

/// Discard a run left `running` from before a crash/restart instead of
/// resuming it (Phase 5.0.1 "破棄"). Purely a Queen DB update — nothing was
/// ever re-registered in memory, so there is no live PTY to kill and no
/// registry entry to touch. `QueenStore::mark_workflow_abandoned` sets
/// `state = 'cancelled'`, so `load_config`'s resume-detection query never
/// surfaces this run_id again.
pub fn abandon_workflow(
    config: &ConfigManager,
    store: &QueenStore,
    run_id: &str,
) -> Result<(), String> {
    let (_cfg, project_dir) = config
        .current()
        .ok_or_else(|| "no config loaded (call load_config first)".to_string())?;
    store.mark_workflow_abandoned(&project_dir, run_id)
}

// -----------------------------------------------------------------------------
// Phase 5.0.0.c: DAG progression driver
// -----------------------------------------------------------------------------
//
// Two independent completion signals feed the driver:
//
//   route 1 (process exit)   — the step's PTY child exited; `classify_session_exit`
//                                maps its exit code to Succeeded/Failed.
//   route 2 (semantic done)  — the step's agent announced completion via its
//                                own output (`AgentStatus::Done`, detected by
//                                `agent_status.rs` and broadcast on the global
//                                `agent-status` event) while its pane is still
//                                alive. `StatusView` is the shared, thread-safe
//                                bridge from that event listener to the driver
//                                loop.
//
// The driver itself is intentionally poll-based (`driver_loop` ticks every
// `DRIVER_TICK`), not event-driven: `advance_run` re-derives what *should*
// happen from the run's current outcomes + the workflow's static DAG shape
// every tick, so a missed or duplicated wakeup is harmless (idempotent).

/// Latest known `AgentStatus` per session id, fed by the `agent-status` event
/// listener (`spawn_status_listener`) and consumed by `detect_completions`.
/// This is completion "route 2" — see the module doc comment above.
#[derive(Default)]
pub struct StatusView {
    inner: Mutex<HashMap<u32, AgentStatus>>,
}

impl StatusView {
    pub fn new() -> Self {
        Self::default()
    }

    /// Record the latest status observed for a session. Overwrites any prior
    /// value; only the most recent status matters for completion detection.
    pub fn record(&self, session_id: u32, status: AgentStatus) {
        if let Ok(mut g) = self.inner.lock() {
            g.insert(session_id, status);
        }
    }

    /// True if the session's last-known status is `Done`. `false` (not an
    /// `Option`) for a session that was never observed, so callers can use
    /// this directly as a completion predicate without an extra `unwrap_or`.
    pub fn semantic_done(&self, session_id: u32) -> bool {
        self.inner
            .lock()
            .ok()
            .and_then(|g| g.get(&session_id).copied())
            .map(|status| status == AgentStatus::Done)
            .unwrap_or(false)
    }

    /// Drop a session's tracked status. Called once the driver has consumed a
    /// completion, so that a later-reused session id does not inherit a stale
    /// `Done` from a previous, unrelated step.
    pub fn forget(&self, session_id: u32) {
        if let Ok(mut g) = self.inner.lock() {
            g.remove(&session_id);
        }
    }
}

// ---------- pure state-machine helpers ----------
//
// Every function in this section is a pure function of its arguments (no
// I/O, no locking) so it can be unit-tested directly without a PTY, a Tauri
// app, or a background thread.

/// Strip a fan-out copy suffix (`"<id>#<k>"`) back to the declaring
/// `WorkflowStep::id`. A no-op for a step_id with no `#` — singular steps,
/// and the already-shipped 5.0.0.a/b root fan-out copies, which
/// intentionally keep the bare id (see `spawn_step`'s callers in
/// `spawn_workflow`). Only steps the 5.0.0.c driver spawns itself
/// (`spawn_ready`) use the suffixed form, to give each copy of a downstream
/// fan-out step an independently trackable row in `WorkflowRun::steps`.
fn base_id(step_id: &str) -> &str {
    match step_id.split_once('#') {
        Some((base, _)) => base,
        None => step_id,
    }
}

/// Whether a `StepState` is terminal (the step will never transition again
/// without external intervention like `cancel_workflow`).
fn is_terminal(state: StepState) -> bool {
    matches!(
        state,
        StepState::Succeeded | StepState::Failed | StepState::Skipped | StepState::Cancelled
    )
}

/// A step's effective join policy, defaulting to `all` when undeclared.
fn effective_join(step: &WorkflowStep) -> JoinOn {
    step.join_on
        .unwrap_or(JoinOn::Named(JoinOnName::All))
}

/// Route-1 completion signal: interpret one PTY's terminal state as step
/// success/failure. Returns `None` while the session has not (yet) exited —
/// the caller should keep waiting, or fall back to route 2 (semantic done).
fn classify_session_exit(state: SessionState, code: Option<i32>) -> Option<StepState> {
    if state != SessionState::Exited {
        return None;
    }
    match code {
        Some(0) => Some(StepState::Succeeded),
        // Non-zero exit, or no code at all (abnormal termination — e.g. the
        // process never even started; see session.rs
        // `restart_failure_marks_session_exited`) both count as failed.
        _ => Some(StepState::Failed),
    }
}

/// Whether a dependency step's fan-out copies collectively satisfy a
/// downstream step's wait on it, per the DEPENDENCY's OWN `join_on` policy —
/// a step's `join_on` describes how ITS copies count as done for anyone
/// depending on it, not the downstream step's policy. `false` (never
/// satisfied) if the dependency has no outcomes at all yet.
fn dep_satisfied(dep_step: &WorkflowStep, outcomes: &[StepOutcome]) -> bool {
    let copies: Vec<&StepOutcome> = outcomes
        .iter()
        .filter(|o| base_id(&o.step_id) == dep_step.id.as_str())
        .collect();
    if copies.is_empty() {
        return false;
    }
    match effective_join(dep_step) {
        JoinOn::Named(JoinOnName::All) => copies.iter().all(|o| o.state == StepState::Succeeded),
        // TODO(5.0.4): `Count(n)` should require >= n successful copies, not
        // just >= 1. MVO folds it into `any` semantics until the join-count
        // bookkeeping (and its interaction with fail-fast) is designed.
        JoinOn::Named(JoinOnName::Any) | JoinOn::Count(_) => {
            copies.iter().any(|o| o.state == StepState::Succeeded)
        }
        // Reply-based join needs a reply-message correlation MVO does not
        // implement (lands in 5.0.4); a dependent gated on it never becomes
        // ready and the run stays Running until cancelled.
        JoinOn::Named(JoinOnName::Reply) => false,
    }
}

/// Steps whose Pending placeholder is still on the run AND whose declared
/// dependencies are all satisfied — the next batch `spawn_ready` should
/// launch. Roots are spawned by `spawn_workflow` itself and so are never
/// Pending by the time the driver runs; this naturally only yields
/// downstream steps once their upstream copies resolve.
fn ready_steps<'a>(wf: &'a WorkflowDef, run: &WorkflowRun) -> Vec<&'a WorkflowStep> {
    wf.steps
        .iter()
        .filter(|step| {
            let pending = run
                .steps
                .iter()
                .any(|o| base_id(&o.step_id) == step.id.as_str() && o.state == StepState::Pending);
            if !pending {
                return false;
            }
            step.depends_on
                .as_deref()
                .unwrap_or(&[])
                .iter()
                .all(|dep_id| {
                    wf.steps
                        .iter()
                        .find(|s| s.id == *dep_id)
                        .map(|dep_step| dep_satisfied(dep_step, &run.steps))
                        .unwrap_or(false)
                })
        })
        .collect()
}

/// Every step that depends, directly or transitively, on `step_id` — the set
/// `failfast_targets` cascades Skipped over when `step_id` can never succeed.
fn transitive_dependents<'a>(wf: &'a WorkflowDef, step_id: &str) -> Vec<&'a WorkflowStep> {
    let mut result: Vec<&WorkflowStep> = Vec::new();
    let mut frontier: Vec<String> = vec![step_id.to_string()];
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    seen.insert(step_id.to_string());
    while let Some(current) = frontier.pop() {
        for step in &wf.steps {
            let depends_on_current = step
                .depends_on
                .as_deref()
                .unwrap_or(&[])
                .contains(&current);
            if depends_on_current && seen.insert(step.id.clone()) {
                result.push(step);
                frontier.push(step.id.clone());
            }
        }
    }
    result
}

/// Step ids (declared, not fan-out-suffixed) that must be cascade-Skipped
/// this tick: every still-`Pending` step transitively downstream of an
/// upstream step whose dependency can now never be satisfied — a
/// `JoinOn::All`/singular step that has already Failed, or an `any`/count
/// joined step every one of whose copies has terminated without a success.
/// MVO defers cooperative cancellation of in-flight fail-fast siblings to
/// 5.0.4, so only `Pending` (not-yet-spawned) steps are targeted here.
fn failfast_targets(wf: &WorkflowDef, run: &WorkflowRun) -> Vec<String> {
    let mut doomed: Vec<String> = Vec::new();
    for step in &wf.steps {
        let copies: Vec<&StepOutcome> = run
            .steps
            .iter()
            .filter(|o| base_id(&o.step_id) == step.id.as_str())
            .collect();
        if copies.is_empty() || !copies.iter().any(|o| o.state == StepState::Failed) {
            continue;
        }
        let unsatisfiable = match effective_join(step) {
            JoinOn::Named(JoinOnName::All) => true,
            JoinOn::Named(JoinOnName::Any) | JoinOn::Count(_) => copies
                .iter()
                .all(|o| is_terminal(o.state) && o.state != StepState::Succeeded),
            JoinOn::Named(JoinOnName::Reply) => true,
        };
        if unsatisfiable {
            doomed.push(step.id.clone());
        }
    }

    let mut targets: Vec<String> = Vec::new();
    for step_id in &doomed {
        for dependent in transitive_dependents(wf, step_id) {
            let pending = run.steps.iter().any(|o| {
                base_id(&o.step_id) == dependent.id.as_str() && o.state == StepState::Pending
            });
            if pending && !targets.contains(&dependent.id) {
                targets.push(dependent.id.clone());
            }
        }
    }
    targets
}

/// Every declared step has at least one outcome copy, and every copy of
/// every declared step is terminal.
fn all_terminal(wf: &WorkflowDef, run: &WorkflowRun) -> bool {
    wf.steps.iter().all(|step| {
        let copies: Vec<&StepOutcome> = run
            .steps
            .iter()
            .filter(|o| base_id(&o.step_id) == step.id.as_str())
            .collect();
        !copies.is_empty() && copies.iter().all(|o| is_terminal(o.state))
    })
}

/// The run-level state implied by the current step outcomes: `Running` while
/// any declared step still has a non-terminal copy, else `Succeeded` only if
/// every step's copies are ALL `Succeeded` (a single Failed or Skipped copy
/// anywhere fails the whole run). Never returns `Cancelled` — that state is
/// only ever set directly by `cancel_workflow`, and `advance_run` never calls
/// this on an already-Cancelled run.
fn finalize_state(wf: &WorkflowDef, run: &WorkflowRun) -> WorkflowState {
    if !all_terminal(wf, run) {
        return WorkflowState::Running;
    }
    let all_succeeded = wf.steps.iter().all(|step| {
        run.steps
            .iter()
            .filter(|o| base_id(&o.step_id) == step.id.as_str())
            .all(|o| o.state == StepState::Succeeded)
    });
    if all_succeeded {
        WorkflowState::Succeeded
    } else {
        WorkflowState::Failed
    }
}

/// Update one outcome's state in place, found by EXACT `step_id` match (a
/// specific fan-out copy or a singular step's bare id). No-op (returns
/// `false`) if no outcome has that id, so callers/tests can assert whether a
/// transition actually landed.
fn set_step_state(
    run: &mut WorkflowRun,
    step_id: &str,
    new_state: StepState,
    error: Option<String>,
) -> bool {
    match run.steps.iter_mut().find(|o| o.step_id == step_id) {
        Some(outcome) => {
            outcome.state = new_state;
            if error.is_some() {
                outcome.error = error;
            }
            true
        }
        None => false,
    }
}

// ---------- side-effecting driver functions ----------

/// Project directory for the currently loaded config. Standalone (rather
/// than inlined at each call site, as `spawn_workflow` still does) because
/// `advance_run` needs it on every tick from just a `ConfigManager` handle.
fn resolve_project_dir(config: &ConfigManager) -> Result<std::path::PathBuf, String> {
    config
        .current()
        .map(|(_, dir)| dir)
        .ok_or_else(|| "no config loaded (call load_config first)".to_string())
}

/// Look up a workflow definition by name from the currently loaded config.
/// Mirrors the lookup inlined in `spawn_workflow`; kept as its own function
/// here since `advance_run` needs it on every tick, independent of any
/// caller-supplied project dir/cols/rows.
fn load_def(config: &ConfigManager, name: &str) -> Result<WorkflowDef, String> {
    let (cfg, _dir) = config
        .current()
        .ok_or_else(|| "no config loaded (call load_config first)".to_string())?;
    cfg.workflows
        .as_ref()
        .and_then(|m| m.get(name))
        .cloned()
        .ok_or_else(|| format!("workflow '{name}' not found in config"))
}

/// Publish a run snapshot on the `workflow-state` event. Callers must pass a
/// value already cloned out of the registry — this is NEVER called while
/// holding the registry's mutex (lock discipline: `WorkflowRegistry::get`/
/// `put` each acquire-and-release internally; emit only happens afterward,
/// against the plain owned/borrowed `WorkflowRun` value that remains).
fn emit_workflow_state<R: Runtime>(app: &AppHandle<R>, run: &WorkflowRun) {
    let _ = app.emit("workflow-state", run);
}

/// Wire string for a `WorkflowState`, used only for the `workflow_runs.state`
/// DB column. The event/JSON wire shape already gets this for free from
/// `#[serde(rename_all = "lowercase")]`; this mirrors it for the write path
/// without deriving `Deserialize` on the enum, which nothing needs to read
/// back — `resume_workflow` only ever resumes a row `list_running_workflow_runs`
/// already filtered to `state = 'running'`, so the DB text is never parsed
/// back into a `WorkflowState`.
fn workflow_state_wire(state: WorkflowState) -> &'static str {
    match state {
        WorkflowState::Pending => "pending",
        WorkflowState::Running => "running",
        WorkflowState::Succeeded => "succeeded",
        WorkflowState::Failed => "failed",
        WorkflowState::Cancelled => "cancelled",
    }
}

/// Best-effort write-through of a run snapshot into the `workflow_runs` table
/// (Phase 5.0.1), so a crash/restart can detect and offer to resume an
/// in-flight run. Called immediately after every `registry.put` in this
/// module (`spawn_workflow`, `cancel_workflow`, `advance_run`) instead of
/// from inside `WorkflowRegistry::put` itself — every call site already has
/// the `QueenStore` + project dir it needs, so `put`'s signature (and every
/// existing caller/test of it) stays untouched. A persistence failure is
/// swallowed, same "best effort" posture already used for kickoff delivery:
/// the in-memory registry remains authoritative for the running app either
/// way, so only a crash before the NEXT successful write would lose
/// resumability for this one transition.
fn persist_run(store: &QueenStore, project_dir: &std::path::Path, run: &WorkflowRun) {
    let Ok(steps_json) = serde_json::to_string(&run.steps) else {
        return;
    };
    let _ = store.upsert_workflow_run(
        project_dir,
        &run.run_id,
        &run.name,
        workflow_state_wire(run.state),
        run.started_at_ms as i64,
        run.ended_at_ms.map(|ms| ms as i64),
        &steps_json,
    );
}

/// Route 1 (PTY exit code) + route 2 (semantic `AgentStatus::Done`)
/// completion detection. Mutates every currently-`Running` outcome that has
/// resolved into `Succeeded`/`Failed` in place; returns `true` if anything
/// changed, so the caller knows whether to re-derive fail-fast/ready/final
/// state this tick.
fn detect_completions(manager: &PtyManager, view: &StatusView, run: &mut WorkflowRun) -> bool {
    let sessions = manager.list_sessions();
    let mut changed = false;
    for outcome in &mut run.steps {
        if outcome.state != StepState::Running {
            continue;
        }
        let Some(session_id) = outcome.session_id else {
            continue;
        };
        // Route 2 first: an agent that has semantically finished (its own
        // output announced "done") counts as Succeeded even if its PTY is
        // still alive (e.g. an interactive pane left open after the task).
        if view.semantic_done(session_id) {
            outcome.state = StepState::Succeeded;
            view.forget(session_id);
            changed = true;
            continue;
        }
        // Route 1: the process itself exited.
        let info = sessions.iter().find(|s| s.id == session_id);
        let (state, code) = match info {
            Some(info) => (info.state, info.code),
            // The session vanished from the table entirely (cleaned up
            // out-of-band) — treat like an abnormal exit with no code.
            None => (SessionState::Exited, None),
        };
        if let Some(new_state) = classify_session_exit(state, code) {
            outcome.state = new_state;
            if new_state == StepState::Failed {
                outcome.error = Some(match code {
                    Some(c) => format!("agent process exited with code {c}"),
                    None => "agent process exited abnormally (no exit code)".to_string(),
                });
            }
            view.forget(session_id);
            changed = true;
        }
    }
    changed
}

/// Spawn every currently-ready step (see `ready_steps`), expanding fan-out
/// copies with the `"<id>#<k>"` id convention so each copy is independently
/// trackable in `run.steps`. Mirrors `spawn_workflow`'s root-spawn loop for
/// non-root (dependent) steps. Returns `true` if anything was spawned.
#[allow(clippy::too_many_arguments)]
fn spawn_ready<R: Runtime>(
    app: &AppHandle<R>,
    manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    project_dir: &std::path::Path,
    workflow_name: &str,
    wf: &WorkflowDef,
    run: &mut WorkflowRun,
    cols: u16,
    rows: u16,
) -> bool {
    let ready: Vec<WorkflowStep> = ready_steps(wf, run).into_iter().cloned().collect();
    let mut changed = false;
    for step in &ready {
        let copies = match (wf.pattern, step.fan_out) {
            (WorkflowPattern::FanOut, Some(n)) if n >= 2 => n as usize,
            _ => 1,
        };
        // Remove the single Pending placeholder `spawn_workflow` inserted for
        // this step; it is replaced below by one outcome per copy.
        run.steps
            .retain(|o| o.step_id != step.id || o.state != StepState::Pending);
        let reuse_existing = copies == 1;
        for k in 0..copies {
            let step_id = if copies >= 2 {
                format!("{}#{k}", step.id)
            } else {
                step.id.clone()
            };
            let mut outcome = spawn_step(app, manager, config, step, reuse_existing, cols, rows);
            outcome.step_id = step_id;
            if outcome.state == StepState::Running {
                if let Err(err) = deliver_kickoff(store, project_dir, workflow_name, step) {
                    let base = outcome.error.clone().unwrap_or_default();
                    outcome.error = Some(if base.is_empty() {
                        format!("kickoff delivery failed: {err}")
                    } else {
                        format!("{base}; kickoff delivery failed: {err}")
                    });
                }
            }
            run.steps.push(outcome);
            changed = true;
        }
    }
    if changed {
        run.steps.sort_by_key(|o| {
            wf.steps
                .iter()
                .position(|s| s.id == base_id(&o.step_id))
                .unwrap_or(usize::MAX)
        });
    }
    changed
}

/// Advance one run by exactly one tick: detect completions, cascade
/// fail-fast Skips, spawn any newly-ready downstream steps, and
/// finalize/emit the run's state. Standalone and thread-free — this is what
/// `driver_loop` calls on a schedule, and what tests call directly to assert
/// transitions without racing a background thread.
#[allow(clippy::too_many_arguments)]
fn advance_run<R: Runtime>(
    app: &AppHandle<R>,
    manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    registry: &WorkflowRegistry,
    view: &StatusView,
    run_id: &str,
) {
    let Some(mut run) = registry.get(run_id) else {
        return;
    };
    if matches!(
        run.state,
        WorkflowState::Succeeded | WorkflowState::Failed | WorkflowState::Cancelled
    ) {
        return;
    }
    // Config unloaded / workflow removed mid-run: nothing to advance
    // against. Leave the run exactly as-is for this tick.
    let Ok(wf) = load_def(config, &run.name) else {
        return;
    };
    let Ok(project_dir) = resolve_project_dir(config) else {
        return;
    };

    let mut changed = detect_completions(manager, view, &mut run);

    for step_id in failfast_targets(&wf, &run) {
        let skipped = set_step_state(
            &mut run,
            &step_id,
            StepState::Skipped,
            Some("skipped: an upstream dependency failed (fail-fast)".to_string()),
        );
        changed = changed || skipped;
    }

    // Hoist the fields borrowed alongside `&mut run` — the borrow checker
    // (rightly) refuses `&run.name` and `&mut run` in one call.
    let workflow_name = run.name.clone();
    let (cols, rows) = (run.cols, run.rows);
    let spawned = spawn_ready(
        app,
        manager,
        config,
        store,
        &project_dir,
        &workflow_name,
        &wf,
        &mut run,
        cols,
        rows,
    );
    changed = changed || spawned;

    let new_state = finalize_state(&wf, &run);
    if new_state != run.state {
        run.state = new_state;
        if matches!(new_state, WorkflowState::Succeeded | WorkflowState::Failed) {
            run.ended_at_ms = Some(now_ms());
        }
        changed = true;
    }

    if changed {
        registry.put(run.clone());
        persist_run(store, &project_dir, &run);
        emit_workflow_state(app, &run);
    }
}

/// One driver tick across every non-terminal run in the registry.
fn advance_all<R: Runtime>(
    app: &AppHandle<R>,
    manager: &PtyManager,
    config: &ConfigManager,
    store: &QueenStore,
    registry: &WorkflowRegistry,
    view: &StatusView,
) {
    for run in registry.list() {
        if matches!(
            run.state,
            WorkflowState::Succeeded | WorkflowState::Failed | WorkflowState::Cancelled
        ) {
            continue;
        }
        advance_run(app, manager, config, store, registry, view, &run.run_id);
    }
}

/// Minimal payload shape read off the `agent-status` event. Deliberately NOT
/// tied to `agent_status`'s own (private, Serialize-only) payload type —
/// this module only needs `id` + `status` and decodes the wire's lowercase
/// status string itself, so it stays decoupled from that module's internals.
#[derive(Deserialize)]
struct AgentStatusWire {
    id: u32,
    status: String,
}

/// Subscribe to the global `agent-status` event stream and forward `Done`
/// transitions (and any other status) into `StatusView`, so `driver_loop`
/// can observe route-2 completions without polling the agent-status
/// detector's internals directly.
fn spawn_status_listener<R: Runtime>(app: &AppHandle<R>, view: Arc<StatusView>) {
    let _event_id = app.listen("agent-status", move |event| {
        let Ok(wire) = serde_json::from_str::<AgentStatusWire>(event.payload()) else {
            return;
        };
        let status = match wire.status.as_str() {
            "working" => AgentStatus::Working,
            "blocked" => AgentStatus::Blocked,
            "done" => AgentStatus::Done,
            "idle" => AgentStatus::Idle,
            _ => AgentStatus::Unknown,
        };
        view.record(wire.id, status);
    });
}

/// Poll interval for the DAG driver. MVO uses a fixed short poll rather than
/// an event-driven wakeup (the `agent-status` listener only feeds
/// `StatusView`; it does not itself trigger a tick) — the simplest thing
/// that keeps step-to-step latency low without redesigning the PTY exit
/// path to push a "session changed" signal into this module.
const DRIVER_TICK: std::time::Duration = std::time::Duration::from_millis(200);

/// The driver's background loop: forever, sleep one tick then advance every
/// non-terminal run. Fetches managed state fresh every tick (same
/// `app.state::<T>()` pattern as `resource_monitor::start`), so it always
/// sees the current `WorkflowRegistry` / `ConfigManager` / `QueenStore` /
/// `PtyManager` even across a config reload.
fn driver_loop<R: Runtime>(app: &AppHandle<R>, view: &StatusView) {
    loop {
        std::thread::sleep(DRIVER_TICK);
        let manager = app.state::<PtyManager>();
        let config = app.state::<ConfigManager>();
        let store = app.state::<QueenStore>();
        let registry = app.state::<WorkflowRegistry>();
        advance_all(app, &manager, &config, &store, &registry, view);
    }
}

/// Start the Phase 5.0.0.c DAG progression driver: an `agent-status`
/// listener that feeds semantic-done signals into a `StatusView`, plus a
/// background thread that ticks every non-terminal workflow run forward.
/// Call once from `lib.rs` setup, same place as `resource_monitor::start`
/// (this module's Tauri command / MCP-tool wiring lands in 5.0.0.e/f, and
/// THAT patch is what actually calls this from `lib.rs`).
pub fn start_driver<R: Runtime>(app: &AppHandle<R>) {
    let view = Arc::new(StatusView::new());
    spawn_status_listener(app, Arc::clone(&view));
    let app = app.clone();
    std::thread::spawn(move || {
        driver_loop(&app, &view);
    });
}

// -----------------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{parse_config, ConfigManager};

    fn mock_handle() -> tauri::AppHandle<tauri::test::MockRuntime> {
        let app = tauri::test::mock_app();
        app.handle().clone()
    }

    fn harness(yaml: &str) -> (ConfigManager, QueenStore, std::path::PathBuf) {
        let dir = std::env::temp_dir().join(format!(
            "ptygrid-orch-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let config = ConfigManager::new();
        config.set_for_test(dir.clone(), parse_config(yaml).unwrap());
        let store = QueenStore::open_in_memory().unwrap();
        (config, store, dir)
    }

    /// Parse `yaml` and pull out one named workflow definition. Used by the
    /// pure-function tests below instead of hand-built `WorkflowDef`/
    /// `WorkflowStep` struct literals, so those tests don't need to assume
    /// anything about config.rs's exact field set beyond what `parse_config`
    /// already exercises elsewhere in this file's existing tests.
    fn parse_wf(yaml: &str, name: &str) -> WorkflowDef {
        let cfg = parse_config(yaml).expect("fixture yaml should parse");
        cfg.workflows
            .expect("workflows: block should be present")
            .get(name)
            .unwrap_or_else(|| panic!("workflow '{name}' should exist"))
            .clone()
    }

    fn mk_outcome(step_id: &str, session_id: Option<u32>, state: StepState) -> StepOutcome {
        StepOutcome {
            step_id: step_id.to_string(),
            agent: "x".to_string(),
            session_id,
            state,
            attempts: 1,
            error: None,
        }
    }

    const PIPELINE_YAML: &str = "agents:
  - name: a
    cmd: /bin/cat
  - name: b
    cmd: /bin/cat
workflows:
  demo:
    pattern: pipeline
    steps:
      - id: first
        agent: a
        kickoff: hello
      - id: second
        agent: b
        dependsOn: [first]
";

    const FANOUT_YAML: &str = "agents:
  - name: worker
    cmd: /bin/cat
workflows:
  triple:
    pattern: fan-out
    steps:
      - id: candidate
        agent: worker
        fanOut: 3
        joinOn: all
";

    #[test]
    fn spawn_workflow_pipeline_launches_root_and_leaves_downstream_pending() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo", 80, 24,
        )
        .expect("pipeline should spawn root step");

        assert_eq!(run.name, "demo");
        assert_eq!(run.state, WorkflowState::Running);
        assert_eq!(run.steps.len(), 2);
        // Root step: Running with a session id.
        assert_eq!(run.steps[0].step_id, "first");
        assert_eq!(run.steps[0].state, StepState::Running);
        assert!(run.steps[0].session_id.is_some());
        // Downstream step: Pending, no session.
        assert_eq!(run.steps[1].step_id, "second");
        assert_eq!(run.steps[1].state, StepState::Pending);
        assert!(run.steps[1].session_id.is_none());
        // Registry has the run.
        assert!(registry.get(&run.run_id).is_some());

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn spawn_workflow_fanout_launches_n_parallel_root_steps() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(FANOUT_YAML);
        let registry = WorkflowRegistry::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "triple", 80, 24,
        )
        .expect("fan-out should spawn 3 parallel steps");

        assert_eq!(run.state, WorkflowState::Running);
        assert_eq!(run.steps.len(), 3, "fanOut: 3 expands into 3 outcome rows");
        for outcome in &run.steps {
            assert_eq!(outcome.step_id, "candidate");
            assert_eq!(outcome.agent, "worker");
            assert_eq!(outcome.state, StepState::Running);
            assert!(outcome.session_id.is_some());
        }
        // Three live sessions on the grid.
        assert_eq!(manager.list_sessions().len(), 3);

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn cancel_workflow_kills_running_and_marks_pending_cancelled() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo", 80, 24,
        )
        .unwrap();
        let cancelled = cancel_workflow(&manager, &config, &store, &registry, &run.run_id).unwrap();

        assert_eq!(cancelled.state, WorkflowState::Cancelled);
        assert_eq!(cancelled.steps[0].state, StepState::Cancelled);
        assert_eq!(cancelled.steps[1].state, StepState::Cancelled);
        assert!(cancelled.ended_at_ms.is_some());

        // Second cancel is idempotent.
        let again = cancel_workflow(&manager, &config, &store, &registry, &run.run_id).unwrap();
        assert_eq!(again.state, WorkflowState::Cancelled);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn unknown_workflow_and_missing_config_error() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();

        let err = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "nope", 80, 24,
        )
        .unwrap_err();
        assert!(err.contains("'nope'"), "unknown-workflow message: {err}");

        let empty = ConfigManager::new();
        let err = spawn_workflow(&handle, &manager, &empty, &store, &registry, "demo", 80, 24)
            .unwrap_err();
        assert!(
            err.contains("no config loaded"),
            "empty-config message: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn fanout_yaml_parses_pattern_and_fan_out_field() {
        // Diagnostic for the fan-out spawn failure: pin down whether the
        // `pattern: fan-out` YAML value deserializes to WorkflowPattern::FanOut
        // and `fanOut: 3` to fan_out: Some(3). If this test passes, parsing is
        // fine and the bug is in the spawn loop. If it fails, we need to fix
        // the serde attributes on WorkflowPattern / WorkflowStep.
        let cfg =
            crate::config::parse_config(FANOUT_YAML).expect("FANOUT_YAML should parse cleanly");
        let workflows = cfg.workflows.expect("workflows: block should be present");
        let wf = workflows
            .get("triple")
            .expect("workflow 'triple' should exist");
        assert_eq!(
            wf.pattern,
            crate::config::WorkflowPattern::FanOut,
            "pattern: fan-out should deserialize to WorkflowPattern::FanOut, got {:?}",
            wf.pattern
        );
        assert_eq!(wf.steps.len(), 1, "workflow should have 1 declared step");
        assert_eq!(
            wf.steps[0].fan_out,
            Some(3),
            "fanOut: 3 should deserialize to fan_out: Some(3), got {:?}",
            wf.steps[0].fan_out
        );
    }

    #[test]
    fn supervisor_pattern_is_rejected_with_typed_error() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let yaml = "agents:
  - name: a
    cmd: /bin/cat
workflows:
  sup:
    pattern: supervisor
    steps:
      - id: root
        agent: a
      - id: child
        agent: a
        dependsOn: [root]
";
        let (config, store, dir) = harness(yaml);
        let registry = WorkflowRegistry::new();

        let err = spawn_workflow(&handle, &manager, &config, &store, &registry, "sup", 80, 24)
            .unwrap_err();
        assert!(
            err.contains("not implemented in MVO"),
            "supervisor should be a typed defer, got: {err}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    // ------------------------------------------------------------------
    // 5.0.0.c: pure state-machine helper tests
    // ------------------------------------------------------------------

    const CHAIN_YAML: &str = "agents:
  - name: a
    cmd: /bin/cat
  - name: b
    cmd: /bin/cat
  - name: c
    cmd: /bin/cat
workflows:
  chain:
    pattern: pipeline
    steps:
      - id: first
        agent: a
      - id: second
        agent: b
        dependsOn: [first]
      - id: third
        agent: c
        dependsOn: [second]
";

    const FANJOIN_YAML: &str = "agents:
  - name: worker
    cmd: /bin/cat
  - name: reducer
    cmd: /bin/cat
workflows:
  fanjoin:
    pattern: fan-out
    steps:
      - id: candidate
        agent: worker
        fanOut: 3
        joinOn: any
      - id: reduce
        agent: reducer
        dependsOn: [candidate]
";

    const REPLY_YAML: &str = "agents:
  - name: a
    cmd: /bin/cat
  - name: b
    cmd: /bin/cat
workflows:
  replywf:
    pattern: pipeline
    steps:
      - id: first
        agent: a
        joinOn: reply
      - id: second
        agent: b
        dependsOn: [first]
";

    #[test]
    fn base_id_strips_fanout_suffix() {
        assert_eq!(base_id("candidate#0"), "candidate");
        assert_eq!(base_id("candidate#12"), "candidate");
        assert_eq!(base_id("first"), "first");
        assert_eq!(base_id(""), "");
    }

    #[test]
    fn is_terminal_classifies_states() {
        assert!(!is_terminal(StepState::Pending));
        assert!(!is_terminal(StepState::Running));
        assert!(is_terminal(StepState::Succeeded));
        assert!(is_terminal(StepState::Failed));
        assert!(is_terminal(StepState::Skipped));
        assert!(is_terminal(StepState::Cancelled));
    }

    #[test]
    fn effective_join_defaults_to_all_and_honors_explicit_any() {
        let wf = parse_wf(FANJOIN_YAML, "fanjoin");
        let candidate = wf.steps.iter().find(|s| s.id == "candidate").unwrap();
        assert!(matches!(
            effective_join(candidate),
            JoinOn::Named(JoinOnName::Any)
        ));
        let reduce = wf.steps.iter().find(|s| s.id == "reduce").unwrap();
        // No `joinOn:` declared on `reduce` -> defaults to `all`.
        assert!(matches!(
            effective_join(reduce),
            JoinOn::Named(JoinOnName::All)
        ));
    }

    #[test]
    fn classify_session_exit_maps_codes_to_step_state() {
        assert_eq!(classify_session_exit(SessionState::Running, None), None);
        assert_eq!(classify_session_exit(SessionState::Starting, Some(0)), None);
        assert_eq!(
            classify_session_exit(SessionState::Exited, Some(0)),
            Some(StepState::Succeeded)
        );
        assert_eq!(
            classify_session_exit(SessionState::Exited, Some(1)),
            Some(StepState::Failed)
        );
        assert_eq!(
            classify_session_exit(SessionState::Exited, None),
            Some(StepState::Failed)
        );
    }

    #[test]
    fn dep_satisfied_all_requires_every_copy_succeeded() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let first = wf.steps.iter().find(|s| s.id == "first").unwrap();

        assert!(!dep_satisfied(
            first,
            &[mk_outcome("first", Some(1), StepState::Running)]
        ));
        assert!(dep_satisfied(
            first,
            &[mk_outcome("first", Some(1), StepState::Succeeded)]
        ));
        assert!(!dep_satisfied(
            first,
            &[mk_outcome("first", Some(1), StepState::Failed)]
        ));
        // No outcomes at all for this step yet -> not satisfied.
        assert!(!dep_satisfied(first, &[]));
    }

    #[test]
    fn dep_satisfied_any_requires_one_success_among_copies() {
        let wf = parse_wf(FANJOIN_YAML, "fanjoin");
        let candidate = wf.steps.iter().find(|s| s.id == "candidate").unwrap();

        let mixed = vec![
            mk_outcome("candidate#0", Some(1), StepState::Failed),
            mk_outcome("candidate#1", Some(2), StepState::Succeeded),
            mk_outcome("candidate#2", Some(3), StepState::Running),
        ];
        assert!(dep_satisfied(candidate, &mixed));

        let none_yet = vec![
            mk_outcome("candidate#0", Some(1), StepState::Failed),
            mk_outcome("candidate#1", Some(2), StepState::Running),
        ];
        assert!(!dep_satisfied(candidate, &none_yet));
    }

    #[test]
    fn dep_satisfied_reply_join_is_always_false() {
        let wf = parse_wf(REPLY_YAML, "replywf");
        let first = wf.steps.iter().find(|s| s.id == "first").unwrap();
        let succeeded = vec![mk_outcome("first", Some(1), StepState::Succeeded)];
        assert!(!dep_satisfied(first, &succeeded));
    }

    #[test]
    fn ready_steps_returns_pending_steps_whose_deps_are_satisfied() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "chain".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![
                mk_outcome("first", Some(1), StepState::Succeeded),
                mk_outcome("second", None, StepState::Pending),
                mk_outcome("third", None, StepState::Pending),
            ],
            cols: 80,
            rows: 24,
        };
        let ready = ready_steps(&wf, &run);
        let ids: Vec<&str> = ready.iter().map(|s| s.id.as_str()).collect();
        assert_eq!(ids, vec!["second"]);
    }

    #[test]
    fn transitive_dependents_walks_the_full_chain() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let mut ids: Vec<&str> = transitive_dependents(&wf, "first")
            .iter()
            .map(|s| s.id.as_str())
            .collect();
        ids.sort();
        assert_eq!(ids, vec!["second", "third"]);

        assert!(transitive_dependents(&wf, "third").is_empty());
    }

    #[test]
    fn failfast_targets_skips_pending_dependents_of_a_doomed_step() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "chain".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![
                mk_outcome("first", Some(1), StepState::Failed),
                mk_outcome("second", None, StepState::Pending),
                mk_outcome("third", None, StepState::Pending),
            ],
            cols: 80,
            rows: 24,
        };
        let mut targets = failfast_targets(&wf, &run);
        targets.sort();
        assert_eq!(targets, vec!["second".to_string(), "third".to_string()]);
    }

    #[test]
    fn failfast_targets_ignores_partial_failure_under_any_join() {
        let wf = parse_wf(FANJOIN_YAML, "fanjoin");
        let run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "fanjoin".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![
                mk_outcome("candidate#0", Some(1), StepState::Failed),
                mk_outcome("candidate#1", Some(2), StepState::Running),
                mk_outcome("candidate#2", Some(3), StepState::Running),
                mk_outcome("reduce", None, StepState::Pending),
            ],
            cols: 80,
            rows: 24,
        };
        assert!(failfast_targets(&wf, &run).is_empty());
    }

    #[test]
    fn all_terminal_requires_every_declared_step_fully_resolved() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let mut run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "chain".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![
                mk_outcome("first", Some(1), StepState::Succeeded),
                mk_outcome("second", None, StepState::Pending),
                mk_outcome("third", None, StepState::Pending),
            ],
            cols: 80,
            rows: 24,
        };
        assert!(!all_terminal(&wf, &run));

        run.steps[1].state = StepState::Succeeded;
        run.steps[2].state = StepState::Skipped;
        assert!(all_terminal(&wf, &run));
    }

    #[test]
    fn finalize_state_succeeds_only_when_every_copy_succeeded() {
        let wf = parse_wf(CHAIN_YAML, "chain");
        let mut run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "chain".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![
                mk_outcome("first", Some(1), StepState::Succeeded),
                mk_outcome("second", Some(2), StepState::Succeeded),
                mk_outcome("third", Some(3), StepState::Succeeded),
            ],
            cols: 80,
            rows: 24,
        };
        assert_eq!(finalize_state(&wf, &run), WorkflowState::Succeeded);

        run.steps[2].state = StepState::Skipped;
        assert_eq!(finalize_state(&wf, &run), WorkflowState::Failed);

        run.steps[2].state = StepState::Running;
        assert_eq!(finalize_state(&wf, &run), WorkflowState::Running);
    }

    #[test]
    fn set_step_state_updates_exact_match_and_no_ops_otherwise() {
        let mut run = WorkflowRun {
            run_id: "r1".to_string(),
            name: "chain".to_string(),
            state: WorkflowState::Running,
            started_at_ms: 0,
            ended_at_ms: None,
            steps: vec![mk_outcome("second", None, StepState::Pending)],
            cols: 80,
            rows: 24,
        };
        assert!(set_step_state(
            &mut run,
            "second",
            StepState::Skipped,
            Some("blocked".to_string())
        ));
        assert_eq!(run.steps[0].state, StepState::Skipped);
        assert_eq!(run.steps[0].error.as_deref(), Some("blocked"));

        assert!(!set_step_state(
            &mut run,
            "does-not-exist",
            StepState::Failed,
            None
        ));
    }

    // ------------------------------------------------------------------
    // 5.0.0.c: StatusView tests
    // ------------------------------------------------------------------

    #[test]
    fn status_view_records_and_reports_done() {
        let view = StatusView::new();
        assert!(
            !view.semantic_done(42),
            "unseen session id defaults to not-done"
        );
        view.record(42, AgentStatus::Working);
        assert!(!view.semantic_done(42));
        view.record(42, AgentStatus::Done);
        assert!(view.semantic_done(42));
    }

    #[test]
    fn status_view_forget_clears_tracked_status() {
        let view = StatusView::new();
        view.record(7, AgentStatus::Done);
        assert!(view.semantic_done(7));
        view.forget(7);
        assert!(!view.semantic_done(7));
    }

    // ------------------------------------------------------------------
    // 5.0.0.c: wiring tests (advance_run called directly, no driver thread)
    // ------------------------------------------------------------------

    const EXIT0_YAML: &str = "agents:
  - name: a
    cmd: \"exit 0\"
  - name: b
    cmd: /bin/cat
workflows:
  demo3:
    pattern: pipeline
    steps:
      - id: first
        agent: a
      - id: second
        agent: b
        dependsOn: [first]
";

    const EXIT1_YAML: &str = "agents:
  - name: a
    cmd: \"exit 1\"
  - name: b
    cmd: /bin/cat
workflows:
  demo4:
    pattern: pipeline
    steps:
      - id: first
        agent: a
      - id: second
        agent: b
        dependsOn: [first]
";

    #[test]
    fn advance_run_spawns_downstream_step_after_root_exits_zero() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(EXIT0_YAML);
        let registry = WorkflowRegistry::new();
        let view = StatusView::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo3", 80, 24,
        )
        .unwrap();

        // PTY exit is asynchronous (the reader thread notices EOF after the
        // child is reaped), so a single tick may run before "first" has
        // transitioned to Exited. Retry absorbs that instability instead of
        // a fixed sleep, mirroring session.rs's own poll-with-deadline tests.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        let mut second_running = false;
        while std::time::Instant::now() < deadline {
            advance_run(
                &handle,
                &manager,
                &config,
                &store,
                &registry,
                &view,
                &run.run_id,
            );
            let snapshot = registry.get(&run.run_id).unwrap();
            second_running = snapshot.steps.iter().any(|o| {
                o.step_id == "second" && o.state == StepState::Running && o.session_id.is_some()
            });
            if second_running {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(50));
        }
        assert!(
            second_running,
            "downstream step should spawn once the root step exits 0"
        );

        let snapshot = registry.get(&run.run_id).unwrap();
        let first = snapshot
            .steps
            .iter()
            .find(|o| o.step_id == "first")
            .unwrap();
        assert_eq!(first.state, StepState::Succeeded);

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn advance_run_fail_fast_skips_downstream_after_root_exits_nonzero() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(EXIT1_YAML);
        let registry = WorkflowRegistry::new();
        let view = StatusView::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo4", 80, 24,
        )
        .unwrap();

        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        let mut finished = false;
        while std::time::Instant::now() < deadline {
            advance_run(
                &handle,
                &manager,
                &config,
                &store,
                &registry,
                &view,
                &run.run_id,
            );
            let snapshot = registry.get(&run.run_id).unwrap();
            finished = snapshot.state == WorkflowState::Failed;
            if finished {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(50));
        }
        assert!(
            finished,
            "run should finalize Failed after the root step fails"
        );

        let snapshot = registry.get(&run.run_id).unwrap();
        let first = snapshot
            .steps
            .iter()
            .find(|o| o.step_id == "first")
            .unwrap();
        let second = snapshot
            .steps
            .iter()
            .find(|o| o.step_id == "second")
            .unwrap();
        assert_eq!(first.state, StepState::Failed);
        assert_eq!(second.state, StepState::Skipped);
        assert!(snapshot.ended_at_ms.is_some());

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn advance_run_treats_semantic_done_as_success_without_pty_exit() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        // Both steps are long-lived (/bin/cat never exits on its own), so a
        // completion here can ONLY be observed via route 2 (StatusView),
        // never route 1 (PTY exit).
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();
        let view = StatusView::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo", 80, 24,
        )
        .unwrap();
        let first_session = run
            .steps
            .iter()
            .find(|o| o.step_id == "first")
            .and_then(|o| o.session_id)
            .unwrap();

        // Sanity check: the PTY has NOT exited, so route 1 could not have
        // fired even if we waited.
        assert_eq!(
            manager.session_state(first_session),
            Some(SessionState::Running)
        );

        view.record(first_session, AgentStatus::Done);
        advance_run(
            &handle,
            &manager,
            &config,
            &store,
            &registry,
            &view,
            &run.run_id,
        );

        let snapshot = registry.get(&run.run_id).unwrap();
        let first = snapshot
            .steps
            .iter()
            .find(|o| o.step_id == "first")
            .unwrap();
        assert_eq!(first.state, StepState::Succeeded);
        let second = snapshot
            .steps
            .iter()
            .find(|o| o.step_id == "second")
            .unwrap();
        assert_eq!(
            second.state,
            StepState::Running,
            "downstream step should spawn from the route-2 completion"
        );
        assert!(second.session_id.is_some());

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    // ------------------------------------------------------------------
    // 5.0.1: resume_workflow (crash/restart recovery)
    // ------------------------------------------------------------------

    #[test]
    fn resume_workflow_flips_running_steps_to_pending_and_keeps_terminal_ones() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo", 80, 24,
        )
        .unwrap();
        assert_eq!(
            store.list_running_workflow_runs(&dir).unwrap().len(),
            1,
            "spawn_workflow should have write-through persisted the new run"
        );

        // Simulate a crash: the app restarts with a brand new (empty)
        // in-memory registry, same as `WorkflowRegistry::new()` in lib.rs on
        // every launch, while the persisted DB row survives untouched.
        let fresh_registry = WorkflowRegistry::new();

        let resumed = resume_workflow(
            &handle,
            &manager,
            &config,
            &store,
            &fresh_registry,
            &run.run_id,
            80,
            24,
        )
        .unwrap();

        assert_eq!(resumed.run_id, run.run_id);
        assert_eq!(resumed.state, WorkflowState::Running);
        // The root step was Running before the "crash" -> resumed as Pending
        // with no session (its PTY died with the app; the driver respawns it
        // on its next tick).
        let first = resumed.steps.iter().find(|o| o.step_id == "first").unwrap();
        assert_eq!(first.state, StepState::Pending);
        assert!(first.session_id.is_none());
        // The downstream step was already Pending before the "crash" ->
        // stays Pending.
        let second = resumed
            .steps
            .iter()
            .find(|o| o.step_id == "second")
            .unwrap();
        assert_eq!(second.state, StepState::Pending);
        assert!(fresh_registry.get(&run.run_id).is_some());

        // A repeat resume call is idempotent against the now-live registry
        // entry rather than re-deriving from the (stale) persisted snapshot.
        let repeat = resume_workflow(
            &handle,
            &manager,
            &config,
            &store,
            &fresh_registry,
            &run.run_id,
            80,
            24,
        )
        .unwrap();
        assert_eq!(repeat.steps.len(), resumed.steps.len());

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn resume_workflow_errors_when_run_missing_or_definition_gone() {
        let handle = mock_handle();
        let manager = PtyManager::new();
        let (config, store, dir) = harness(PIPELINE_YAML);
        let registry = WorkflowRegistry::new();

        let err = resume_workflow(
            &handle,
            &manager,
            &config,
            &store,
            &registry,
            "wfr_does_not_exist",
            80,
            24,
        )
        .unwrap_err();
        assert!(err.contains("not found"), "unknown run_id message: {err}");

        let run = spawn_workflow(
            &handle, &manager, &config, &store, &registry, "demo", 80, 24,
        )
        .unwrap();
        // Reload a config for the SAME project dir that no longer declares
        // "demo" (edge case: config changed before the user resumed).
        let redefined = ConfigManager::new();
        redefined.set_for_test(dir.clone(), parse_config("agents: []\n").unwrap());
        let err = resume_workflow(
            &handle,
            &manager,
            &redefined,
            &store,
            &WorkflowRegistry::new(),
            &run.run_id,
            80,
            24,
        )
        .unwrap_err();
        assert!(
            err.contains("no longer defined"),
            "stale-definition message: {err}"
        );

        for s in manager.list_sessions() {
            let _ = manager.kill_pty(s.id);
        }
        let _ = std::fs::remove_dir_all(&dir);
    }
}
